dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
filename: mocks.go
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/allisson/secrets/internal/database:
    interfaces:
      TxManager: {}
  github.com/allisson/secrets/internal/keyring:
    interfaces:
      KekUseCase: {}
  github.com/allisson/secrets/internal/auth/domain:
    interfaces:
      AuditLogRepository: {}
      ClientRepository: {}
      TokenRepository: {}
  github.com/allisson/secrets/internal/auth/usecase:
    interfaces:
      AuditLogUseCase: {}
      ClientUseCase: {}
      TokenUseCase: {}
  github.com/allisson/secrets/internal/secrets/domain:
    interfaces:
      SecretRepository: {}
  github.com/allisson/secrets/internal/secrets/usecase:
    interfaces:
      SecretUseCase: {}
  github.com/allisson/secrets/internal/transit/domain:
    interfaces:
      TransitKeyRepository: {}
  github.com/allisson/secrets/internal/transit/usecase:
    interfaces:
      TransitKeyUseCase: {}
  github.com/allisson/secrets/internal/tokenization/domain:
    interfaces:
      TokenizationKeyRepository: {}
      TokenRepository: {}
  github.com/allisson/secrets/internal/tokenization/usecase:
    interfaces:
      TokenizationKeyUseCase: {}
      TokenizationUseCase: {}
