// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/keyring"
	"github.com/allisson/secrets/internal/tokenization/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenizationKeyUseCase creates a new instance of MockTokenizationKeyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenizationKeyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenizationKeyUseCase {
	mock := &MockTokenizationKeyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenizationKeyUseCase is an autogenerated mock type for the TokenizationKeyUseCase type
type MockTokenizationKeyUseCase struct {
	mock.Mock
}

type MockTokenizationKeyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenizationKeyUseCase) EXPECT() *MockTokenizationKeyUseCase_Expecter {
	return &MockTokenizationKeyUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) Create(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm) (*domain.TokenizationKey, error) {
	ret := _mock.Called(ctx, name, formatType, isDeterministic, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.TokenizationKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) (*domain.TokenizationKey, error)); ok {
		return returnFunc(ctx, name, formatType, isDeterministic, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) *domain.TokenizationKey); ok {
		r0 = returnFunc(ctx, name, formatType, isDeterministic, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenizationKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) error); ok {
		r1 = returnFunc(ctx, name, formatType, isDeterministic, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationKeyUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenizationKeyUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - formatType domain.FormatType
//   - isDeterministic bool
//   - alg keyring.Algorithm
func (_e *MockTokenizationKeyUseCase_Expecter) Create(ctx any, name any, formatType any, isDeterministic any, alg any) *MockTokenizationKeyUseCase_Create_Call {
	return &MockTokenizationKeyUseCase_Create_Call{Call: _e.mock.On("Create", ctx, name, formatType, isDeterministic, alg)}
}

func (_c *MockTokenizationKeyUseCase_Create_Call) Run(run func(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm)) *MockTokenizationKeyUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.FormatType
		if args[2] != nil {
			arg2 = args[2].(domain.FormatType)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 keyring.Algorithm
		if args[4] != nil {
			arg4 = args[4].(keyring.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_Create_Call) Return(tokenizationKey *domain.TokenizationKey, err error) *MockTokenizationKeyUseCase_Create_Call {
	_c.Call.Return(tokenizationKey, err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm) (*domain.TokenizationKey, error)) *MockTokenizationKeyUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenizationKeyUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTokenizationKeyUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTokenizationKeyUseCase_Expecter) Delete(ctx any, name any) *MockTokenizationKeyUseCase_Delete_Call {
	return &MockTokenizationKeyUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockTokenizationKeyUseCase_Delete_Call) Run(run func(ctx context.Context, name string)) *MockTokenizationKeyUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_Delete_Call) Return(err error) *MockTokenizationKeyUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockTokenizationKeyUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) GetByName(ctx context.Context, name string) (*domain.TokenizationKey, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.TokenizationKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.TokenizationKey, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.TokenizationKey); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenizationKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationKeyUseCase_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTokenizationKeyUseCase_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTokenizationKeyUseCase_Expecter) GetByName(ctx any, name any) *MockTokenizationKeyUseCase_GetByName_Call {
	return &MockTokenizationKeyUseCase_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTokenizationKeyUseCase_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTokenizationKeyUseCase_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_GetByName_Call) Return(tokenizationKey *domain.TokenizationKey, err error) *MockTokenizationKeyUseCase_GetByName_Call {
	_c.Call.Return(tokenizationKey, err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.TokenizationKey, error)) *MockTokenizationKeyUseCase_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) ListCursor(ctx context.Context, afterName *string, limit int) ([]*domain.TokenizationKey, error) {
	ret := _mock.Called(ctx, afterName, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.TokenizationKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) ([]*domain.TokenizationKey, error)); ok {
		return returnFunc(ctx, afterName, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) []*domain.TokenizationKey); ok {
		r0 = returnFunc(ctx, afterName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TokenizationKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int) error); ok {
		r1 = returnFunc(ctx, afterName, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationKeyUseCase_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockTokenizationKeyUseCase_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterName *string
//   - limit int
func (_e *MockTokenizationKeyUseCase_Expecter) ListCursor(ctx any, afterName any, limit any) *MockTokenizationKeyUseCase_ListCursor_Call {
	return &MockTokenizationKeyUseCase_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterName, limit)}
}

func (_c *MockTokenizationKeyUseCase_ListCursor_Call) Run(run func(ctx context.Context, afterName *string, limit int)) *MockTokenizationKeyUseCase_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_ListCursor_Call) Return(tokenizationKeys []*domain.TokenizationKey, err error) *MockTokenizationKeyUseCase_ListCursor_Call {
	_c.Call.Return(tokenizationKeys, err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterName *string, limit int) ([]*domain.TokenizationKey, error)) *MockTokenizationKeyUseCase_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeleted provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) PurgeDeleted(ctx context.Context, olderThanDays int, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, olderThanDays, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeleted")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (int64, error)); ok {
		return returnFunc(ctx, olderThanDays, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) int64); ok {
		r0 = returnFunc(ctx, olderThanDays, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, olderThanDays, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationKeyUseCase_PurgeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeleted'
type MockTokenizationKeyUseCase_PurgeDeleted_Call struct {
	*mock.Call
}

// PurgeDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThanDays int
//   - dryRun bool
func (_e *MockTokenizationKeyUseCase_Expecter) PurgeDeleted(ctx any, olderThanDays any, dryRun any) *MockTokenizationKeyUseCase_PurgeDeleted_Call {
	return &MockTokenizationKeyUseCase_PurgeDeleted_Call{Call: _e.mock.On("PurgeDeleted", ctx, olderThanDays, dryRun)}
}

func (_c *MockTokenizationKeyUseCase_PurgeDeleted_Call) Run(run func(ctx context.Context, olderThanDays int, dryRun bool)) *MockTokenizationKeyUseCase_PurgeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_PurgeDeleted_Call) Return(n int64, err error) *MockTokenizationKeyUseCase_PurgeDeleted_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_PurgeDeleted_Call) RunAndReturn(run func(ctx context.Context, olderThanDays int, dryRun bool) (int64, error)) *MockTokenizationKeyUseCase_PurgeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockTokenizationKeyUseCase
func (_mock *MockTokenizationKeyUseCase) Rotate(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm) (*domain.TokenizationKey, error) {
	ret := _mock.Called(ctx, name, formatType, isDeterministic, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *domain.TokenizationKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) (*domain.TokenizationKey, error)); ok {
		return returnFunc(ctx, name, formatType, isDeterministic, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) *domain.TokenizationKey); ok {
		r0 = returnFunc(ctx, name, formatType, isDeterministic, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenizationKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.FormatType, bool, keyring.Algorithm) error); ok {
		r1 = returnFunc(ctx, name, formatType, isDeterministic, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationKeyUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockTokenizationKeyUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - formatType domain.FormatType
//   - isDeterministic bool
//   - alg keyring.Algorithm
func (_e *MockTokenizationKeyUseCase_Expecter) Rotate(ctx any, name any, formatType any, isDeterministic any, alg any) *MockTokenizationKeyUseCase_Rotate_Call {
	return &MockTokenizationKeyUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, name, formatType, isDeterministic, alg)}
}

func (_c *MockTokenizationKeyUseCase_Rotate_Call) Run(run func(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm)) *MockTokenizationKeyUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.FormatType
		if args[2] != nil {
			arg2 = args[2].(domain.FormatType)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 keyring.Algorithm
		if args[4] != nil {
			arg4 = args[4].(keyring.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenizationKeyUseCase_Rotate_Call) Return(tokenizationKey *domain.TokenizationKey, err error) *MockTokenizationKeyUseCase_Rotate_Call {
	_c.Call.Return(tokenizationKey, err)
	return _c
}

func (_c *MockTokenizationKeyUseCase_Rotate_Call) RunAndReturn(run func(ctx context.Context, name string, formatType domain.FormatType, isDeterministic bool, alg keyring.Algorithm) (*domain.TokenizationKey, error)) *MockTokenizationKeyUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenizationUseCase creates a new instance of MockTokenizationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenizationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenizationUseCase {
	mock := &MockTokenizationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenizationUseCase is an autogenerated mock type for the TokenizationUseCase type
type MockTokenizationUseCase struct {
	mock.Mock
}

type MockTokenizationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenizationUseCase) EXPECT() *MockTokenizationUseCase_Expecter {
	return &MockTokenizationUseCase_Expecter{mock: &_m.Mock}
}

// CleanupExpired provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) CleanupExpired(ctx context.Context, days int, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, days, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (int64, error)); ok {
		return returnFunc(ctx, days, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) int64); ok {
		r0 = returnFunc(ctx, days, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, days, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationUseCase_CleanupExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpired'
type MockTokenizationUseCase_CleanupExpired_Call struct {
	*mock.Call
}

// CleanupExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - days int
//   - dryRun bool
func (_e *MockTokenizationUseCase_Expecter) CleanupExpired(ctx any, days any, dryRun any) *MockTokenizationUseCase_CleanupExpired_Call {
	return &MockTokenizationUseCase_CleanupExpired_Call{Call: _e.mock.On("CleanupExpired", ctx, days, dryRun)}
}

func (_c *MockTokenizationUseCase_CleanupExpired_Call) Run(run func(ctx context.Context, days int, dryRun bool)) *MockTokenizationUseCase_CleanupExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_CleanupExpired_Call) Return(n int64, err error) *MockTokenizationUseCase_CleanupExpired_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTokenizationUseCase_CleanupExpired_Call) RunAndReturn(run func(ctx context.Context, days int, dryRun bool) (int64, error)) *MockTokenizationUseCase_CleanupExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Detokenize provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) Detokenize(ctx context.Context, token string) ([]byte, map[string]any, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Detokenize")
	}

	var r0 []byte
	var r1 map[string]any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, map[string]any, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) map[string]any); ok {
		r1 = returnFunc(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenizationUseCase_Detokenize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detokenize'
type MockTokenizationUseCase_Detokenize_Call struct {
	*mock.Call
}

// Detokenize is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenizationUseCase_Expecter) Detokenize(ctx any, token any) *MockTokenizationUseCase_Detokenize_Call {
	return &MockTokenizationUseCase_Detokenize_Call{Call: _e.mock.On("Detokenize", ctx, token)}
}

func (_c *MockTokenizationUseCase_Detokenize_Call) Run(run func(ctx context.Context, token string)) *MockTokenizationUseCase_Detokenize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_Detokenize_Call) Return(plaintext []byte, metadata map[string]any, err error) *MockTokenizationUseCase_Detokenize_Call {
	_c.Call.Return(plaintext, metadata, err)
	return _c
}

func (_c *MockTokenizationUseCase_Detokenize_Call) RunAndReturn(run func(ctx context.Context, token string) ([]byte, map[string]any, error)) *MockTokenizationUseCase_Detokenize_Call {
	_c.Call.Return(run)
	return _c
}

// DetokenizeBatch provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) DetokenizeBatch(ctx context.Context, tokens []string) ([][]byte, []map[string]any, error) {
	ret := _mock.Called(ctx, tokens)

	if len(ret) == 0 {
		panic("no return value specified for DetokenizeBatch")
	}

	var r0 [][]byte
	var r1 []map[string]any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([][]byte, []map[string]any, error)); ok {
		return returnFunc(ctx, tokens)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) [][]byte); ok {
		r0 = returnFunc(ctx, tokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) []map[string]any); ok {
		r1 = returnFunc(ctx, tokens)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = returnFunc(ctx, tokens)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenizationUseCase_DetokenizeBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetokenizeBatch'
type MockTokenizationUseCase_DetokenizeBatch_Call struct {
	*mock.Call
}

// DetokenizeBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens []string
func (_e *MockTokenizationUseCase_Expecter) DetokenizeBatch(ctx any, tokens any) *MockTokenizationUseCase_DetokenizeBatch_Call {
	return &MockTokenizationUseCase_DetokenizeBatch_Call{Call: _e.mock.On("DetokenizeBatch", ctx, tokens)}
}

func (_c *MockTokenizationUseCase_DetokenizeBatch_Call) Run(run func(ctx context.Context, tokens []string)) *MockTokenizationUseCase_DetokenizeBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_DetokenizeBatch_Call) Return(plaintexts [][]byte, metadatas []map[string]any, err error) *MockTokenizationUseCase_DetokenizeBatch_Call {
	_c.Call.Return(plaintexts, metadatas, err)
	return _c
}

func (_c *MockTokenizationUseCase_DetokenizeBatch_Call) RunAndReturn(run func(ctx context.Context, tokens []string) ([][]byte, []map[string]any, error)) *MockTokenizationUseCase_DetokenizeBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) Revoke(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenizationUseCase_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenizationUseCase_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenizationUseCase_Expecter) Revoke(ctx any, token any) *MockTokenizationUseCase_Revoke_Call {
	return &MockTokenizationUseCase_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token)}
}

func (_c *MockTokenizationUseCase_Revoke_Call) Run(run func(ctx context.Context, token string)) *MockTokenizationUseCase_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_Revoke_Call) Return(err error) *MockTokenizationUseCase_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenizationUseCase_Revoke_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenizationUseCase_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Tokenize provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) Tokenize(ctx context.Context, keyName string, plaintext []byte, metadata map[string]any, expiresAt *time.Time) (*domain.Token, error) {
	ret := _mock.Called(ctx, keyName, plaintext, metadata, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Tokenize")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]any, *time.Time) (*domain.Token, error)); ok {
		return returnFunc(ctx, keyName, plaintext, metadata, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, map[string]any, *time.Time) *domain.Token); ok {
		r0 = returnFunc(ctx, keyName, plaintext, metadata, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte, map[string]any, *time.Time) error); ok {
		r1 = returnFunc(ctx, keyName, plaintext, metadata, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationUseCase_Tokenize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tokenize'
type MockTokenizationUseCase_Tokenize_Call struct {
	*mock.Call
}

// Tokenize is a helper method to define mock.On call
//   - ctx context.Context
//   - keyName string
//   - plaintext []byte
//   - metadata map[string]any
//   - expiresAt *time.Time
func (_e *MockTokenizationUseCase_Expecter) Tokenize(ctx any, keyName any, plaintext any, metadata any, expiresAt any) *MockTokenizationUseCase_Tokenize_Call {
	return &MockTokenizationUseCase_Tokenize_Call{Call: _e.mock.On("Tokenize", ctx, keyName, plaintext, metadata, expiresAt)}
}

func (_c *MockTokenizationUseCase_Tokenize_Call) Run(run func(ctx context.Context, keyName string, plaintext []byte, metadata map[string]any, expiresAt *time.Time)) *MockTokenizationUseCase_Tokenize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_Tokenize_Call) Return(token *domain.Token, err error) *MockTokenizationUseCase_Tokenize_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenizationUseCase_Tokenize_Call) RunAndReturn(run func(ctx context.Context, keyName string, plaintext []byte, metadata map[string]any, expiresAt *time.Time) (*domain.Token, error)) *MockTokenizationUseCase_Tokenize_Call {
	_c.Call.Return(run)
	return _c
}

// TokenizeBatch provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) TokenizeBatch(ctx context.Context, keyName string, plaintexts [][]byte, metadatas []map[string]any, expiresAt *time.Time) ([]*domain.Token, error) {
	ret := _mock.Called(ctx, keyName, plaintexts, metadatas, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for TokenizeBatch")
	}

	var r0 []*domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, [][]byte, []map[string]any, *time.Time) ([]*domain.Token, error)); ok {
		return returnFunc(ctx, keyName, plaintexts, metadatas, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, [][]byte, []map[string]any, *time.Time) []*domain.Token); ok {
		r0 = returnFunc(ctx, keyName, plaintexts, metadatas, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, [][]byte, []map[string]any, *time.Time) error); ok {
		r1 = returnFunc(ctx, keyName, plaintexts, metadatas, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationUseCase_TokenizeBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenizeBatch'
type MockTokenizationUseCase_TokenizeBatch_Call struct {
	*mock.Call
}

// TokenizeBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - keyName string
//   - plaintexts [][]byte
//   - metadatas []map[string]any
//   - expiresAt *time.Time
func (_e *MockTokenizationUseCase_Expecter) TokenizeBatch(ctx any, keyName any, plaintexts any, metadatas any, expiresAt any) *MockTokenizationUseCase_TokenizeBatch_Call {
	return &MockTokenizationUseCase_TokenizeBatch_Call{Call: _e.mock.On("TokenizeBatch", ctx, keyName, plaintexts, metadatas, expiresAt)}
}

func (_c *MockTokenizationUseCase_TokenizeBatch_Call) Run(run func(ctx context.Context, keyName string, plaintexts [][]byte, metadatas []map[string]any, expiresAt *time.Time)) *MockTokenizationUseCase_TokenizeBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 [][]byte
		if args[2] != nil {
			arg2 = args[2].([][]byte)
		}
		var arg3 []map[string]any
		if args[3] != nil {
			arg3 = args[3].([]map[string]any)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_TokenizeBatch_Call) Return(tokens []*domain.Token, err error) *MockTokenizationUseCase_TokenizeBatch_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockTokenizationUseCase_TokenizeBatch_Call) RunAndReturn(run func(ctx context.Context, keyName string, plaintexts [][]byte, metadatas []map[string]any, expiresAt *time.Time) ([]*domain.Token, error)) *MockTokenizationUseCase_TokenizeBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockTokenizationUseCase
func (_mock *MockTokenizationUseCase) Validate(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenizationUseCase_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockTokenizationUseCase_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenizationUseCase_Expecter) Validate(ctx any, token any) *MockTokenizationUseCase_Validate_Call {
	return &MockTokenizationUseCase_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *MockTokenizationUseCase_Validate_Call) Run(run func(ctx context.Context, token string)) *MockTokenizationUseCase_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenizationUseCase_Validate_Call) Return(b bool, err error) *MockTokenizationUseCase_Validate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTokenizationUseCase_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockTokenizationUseCase_Validate_Call {
	_c.Call.Return(run)
	return _c
}
