// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDekRepository is an autogenerated mock type for the DekRepository type
type MockDekRepository struct {
	mock.Mock
}

type MockDekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDekRepository) EXPECT() *MockDekRepository_Expecter {
	return &MockDekRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dek
func (_m *MockDekRepository) Create(ctx context.Context, dek *domain.Dek) error {
	ret := _m.Called(ctx, dek)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Dek) error); ok {
		r0 = rf(ctx, dek)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDekRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDekRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dek *domain.Dek
func (_e *MockDekRepository_Expecter) Create(ctx interface{}, dek interface{}) *MockDekRepository_Create_Call {
	return &MockDekRepository_Create_Call{Call: _e.mock.On("Create", ctx, dek)}
}

func (_c *MockDekRepository_Create_Call) Run(run func(ctx context.Context, dek *domain.Dek)) *MockDekRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Dek))
	})
	return _c
}

func (_c *MockDekRepository_Create_Call) Return(_a0 error) *MockDekRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDekRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Dek) error) *MockDekRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, dekID
func (_m *MockDekRepository) Get(ctx context.Context, dekID uuid.UUID) (*domain.Dek, error) {
	ret := _m.Called(ctx, dekID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Dek
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Dek, error)); ok {
		return rf(ctx, dekID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Dek); ok {
		r0 = rf(ctx, dekID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dek)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, dekID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDekRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDekRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dekID uuid.UUID
func (_e *MockDekRepository_Expecter) Get(ctx interface{}, dekID interface{}) *MockDekRepository_Get_Call {
	return &MockDekRepository_Get_Call{Call: _e.mock.On("Get", ctx, dekID)}
}

func (_c *MockDekRepository_Get_Call) Run(run func(ctx context.Context, dekID uuid.UUID)) *MockDekRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDekRepository_Get_Call) Return(_a0 *domain.Dek, _a1 error) *MockDekRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDekRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Dek, error)) *MockDekRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDekRepository creates a new instance of MockDekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDekRepository {
	mock := &MockDekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
