// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/allisson/secrets/internal/crypto/domain"
	domain0 "github.com/allisson/secrets/internal/transit/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDekRepository creates a new instance of MockDekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDekRepository {
	mock := &MockDekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDekRepository is an autogenerated mock type for the DekRepository type
type MockDekRepository struct {
	mock.Mock
}

type MockDekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDekRepository) EXPECT() *MockDekRepository_Expecter {
	return &MockDekRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDekRepository
func (_mock *MockDekRepository) Create(ctx context.Context, dek *domain.Dek) error {
	ret := _mock.Called(ctx, dek)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Dek) error); ok {
		r0 = returnFunc(ctx, dek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDekRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDekRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dek *domain.Dek
func (_e *MockDekRepository_Expecter) Create(ctx interface{}, dek interface{}) *MockDekRepository_Create_Call {
	return &MockDekRepository_Create_Call{Call: _e.mock.On("Create", ctx, dek)}
}

func (_c *MockDekRepository_Create_Call) Run(run func(ctx context.Context, dek *domain.Dek)) *MockDekRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Dek
		if args[1] != nil {
			arg1 = args[1].(*domain.Dek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDekRepository_Create_Call) Return(err error) *MockDekRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDekRepository_Create_Call) RunAndReturn(run func(ctx context.Context, dek *domain.Dek) error) *MockDekRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDekRepository
func (_mock *MockDekRepository) Get(ctx context.Context, dekID uuid.UUID) (*domain.Dek, error) {
	ret := _mock.Called(ctx, dekID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Dek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Dek, error)); ok {
		return returnFunc(ctx, dekID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Dek); ok {
		r0 = returnFunc(ctx, dekID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dek)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, dekID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDekRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDekRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - dekID uuid.UUID
func (_e *MockDekRepository_Expecter) Get(ctx interface{}, dekID interface{}) *MockDekRepository_Get_Call {
	return &MockDekRepository_Get_Call{Call: _e.mock.On("Get", ctx, dekID)}
}

func (_c *MockDekRepository_Get_Call) Run(run func(ctx context.Context, dekID uuid.UUID)) *MockDekRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDekRepository_Get_Call) Return(dek *domain.Dek, err error) *MockDekRepository_Get_Call {
	_c.Call.Return(dek, err)
	return _c
}

func (_c *MockDekRepository_Get_Call) RunAndReturn(run func(ctx context.Context, dekID uuid.UUID) (*domain.Dek, error)) *MockDekRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitKeyRepository creates a new instance of MockTransitKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitKeyRepository {
	mock := &MockTransitKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransitKeyRepository is an autogenerated mock type for the TransitKeyRepository type
type MockTransitKeyRepository struct {
	mock.Mock
}

type MockTransitKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitKeyRepository) EXPECT() *MockTransitKeyRepository_Expecter {
	return &MockTransitKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) Create(ctx context.Context, transitKey *domain0.TransitKey) error {
	ret := _mock.Called(ctx, transitKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain0.TransitKey) error); ok {
		r0 = returnFunc(ctx, transitKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransitKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransitKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKey *domain0.TransitKey
func (_e *MockTransitKeyRepository_Expecter) Create(ctx interface{}, transitKey interface{}) *MockTransitKeyRepository_Create_Call {
	return &MockTransitKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, transitKey)}
}

func (_c *MockTransitKeyRepository_Create_Call) Run(run func(ctx context.Context, transitKey *domain0.TransitKey)) *MockTransitKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain0.TransitKey
		if args[1] != nil {
			arg1 = args[1].(*domain0.TransitKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) Return(err error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, transitKey *domain0.TransitKey) error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) Delete(ctx context.Context, transitKeyID uuid.UUID) error {
	ret := _mock.Called(ctx, transitKeyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, transitKeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransitKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransitKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKeyID uuid.UUID
func (_e *MockTransitKeyRepository_Expecter) Delete(ctx interface{}, transitKeyID interface{}) *MockTransitKeyRepository_Delete_Call {
	return &MockTransitKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, transitKeyID)}
}

func (_c *MockTransitKeyRepository_Delete_Call) Run(run func(ctx context.Context, transitKeyID uuid.UUID)) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) Return(err error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, transitKeyID uuid.UUID) error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) GetByName(ctx context.Context, name string) (*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain0.TransitKey); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTransitKeyRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransitKeyRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockTransitKeyRepository_GetByName_Call {
	return &MockTransitKeyRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTransitKeyRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) Return(transitKey *domain0.TransitKey, err error) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain0.TransitKey, error)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNameAndVersion provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) GetByNameAndVersion(ctx context.Context, name string, version uint) (*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndVersion")
	}

	var r0 *domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) (*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, name, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) *domain0.TransitKey); ok {
		r0 = returnFunc(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_GetByNameAndVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNameAndVersion'
type MockTransitKeyRepository_GetByNameAndVersion_Call struct {
	*mock.Call
}

// GetByNameAndVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version uint
func (_e *MockTransitKeyRepository_Expecter) GetByNameAndVersion(ctx interface{}, name interface{}, version interface{}) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	return &MockTransitKeyRepository_GetByNameAndVersion_Call{Call: _e.mock.On("GetByNameAndVersion", ctx, name, version)}
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Run(run func(ctx context.Context, name string, version uint)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Return(transitKey *domain0.TransitKey, err error) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) RunAndReturn(run func(ctx context.Context, name string, version uint) (*domain0.TransitKey, error)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) List(ctx context.Context, offset int, limit int) ([]*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain0.TransitKey); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransitKeyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockTransitKeyRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockTransitKeyRepository_List_Call {
	return &MockTransitKeyRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockTransitKeyRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockTransitKeyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_List_Call) Return(transitKeys []*domain0.TransitKey, err error) *MockTransitKeyRepository_List_Call {
	_c.Call.Return(transitKeys, err)
	return _c
}

func (_c *MockTransitKeyRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*domain0.TransitKey, error)) *MockTransitKeyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitKeyUseCase creates a new instance of MockTransitKeyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitKeyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitKeyUseCase {
	mock := &MockTransitKeyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransitKeyUseCase is an autogenerated mock type for the TransitKeyUseCase type
type MockTransitKeyUseCase struct {
	mock.Mock
}

type MockTransitKeyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitKeyUseCase) EXPECT() *MockTransitKeyUseCase_Expecter {
	return &MockTransitKeyUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) Create(ctx context.Context, name string, alg domain.Algorithm) (*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, name, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) (*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, name, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) *domain0.TransitKey); ok {
		r0 = returnFunc(ctx, name, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Algorithm) error); ok {
		r1 = returnFunc(ctx, name, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransitKeyUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - alg domain.Algorithm
func (_e *MockTransitKeyUseCase_Expecter) Create(ctx interface{}, name interface{}, alg interface{}) *MockTransitKeyUseCase_Create_Call {
	return &MockTransitKeyUseCase_Create_Call{Call: _e.mock.On("Create", ctx, name, alg)}
}

func (_c *MockTransitKeyUseCase_Create_Call) Run(run func(ctx context.Context, name string, alg domain.Algorithm)) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Create_Call) Return(transitKey *domain0.TransitKey, err error) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, name string, alg domain.Algorithm) (*domain0.TransitKey, error)) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) Decrypt(ctx context.Context, name string, ciphertext string) (*domain0.EncryptedBlob, error) {
	ret := _mock.Called(ctx, name, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 *domain0.EncryptedBlob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain0.EncryptedBlob, error)); ok {
		return returnFunc(ctx, name, ciphertext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain0.EncryptedBlob); ok {
		r0 = returnFunc(ctx, name, ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.EncryptedBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, ciphertext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyUseCase_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockTransitKeyUseCase_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ciphertext string
func (_e *MockTransitKeyUseCase_Expecter) Decrypt(ctx interface{}, name interface{}, ciphertext interface{}) *MockTransitKeyUseCase_Decrypt_Call {
	return &MockTransitKeyUseCase_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, name, ciphertext)}
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) Run(run func(ctx context.Context, name string, ciphertext string)) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) Return(encryptedBlob *domain0.EncryptedBlob, err error) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Return(encryptedBlob, err)
	return _c
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) RunAndReturn(run func(ctx context.Context, name string, ciphertext string) (*domain0.EncryptedBlob, error)) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) Delete(ctx context.Context, transitKeyID uuid.UUID) error {
	ret := _mock.Called(ctx, transitKeyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, transitKeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransitKeyUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransitKeyUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKeyID uuid.UUID
func (_e *MockTransitKeyUseCase_Expecter) Delete(ctx interface{}, transitKeyID interface{}) *MockTransitKeyUseCase_Delete_Call {
	return &MockTransitKeyUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, transitKeyID)}
}

func (_c *MockTransitKeyUseCase_Delete_Call) Run(run func(ctx context.Context, transitKeyID uuid.UUID)) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Delete_Call) Return(err error) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransitKeyUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, transitKeyID uuid.UUID) error) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) Encrypt(ctx context.Context, name string, plaintext []byte) (*domain0.EncryptedBlob, error) {
	ret := _mock.Called(ctx, name, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *domain0.EncryptedBlob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (*domain0.EncryptedBlob, error)); ok {
		return returnFunc(ctx, name, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) *domain0.EncryptedBlob); ok {
		r0 = returnFunc(ctx, name, plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.EncryptedBlob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, name, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyUseCase_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockTransitKeyUseCase_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - plaintext []byte
func (_e *MockTransitKeyUseCase_Expecter) Encrypt(ctx interface{}, name interface{}, plaintext interface{}) *MockTransitKeyUseCase_Encrypt_Call {
	return &MockTransitKeyUseCase_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, name, plaintext)}
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) Run(run func(ctx context.Context, name string, plaintext []byte)) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) Return(encryptedBlob *domain0.EncryptedBlob, err error) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Return(encryptedBlob, err)
	return _c
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) RunAndReturn(run func(ctx context.Context, name string, plaintext []byte) (*domain0.EncryptedBlob, error)) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) List(ctx context.Context, offset int, limit int) ([]*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain0.TransitKey); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransitKeyUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockTransitKeyUseCase_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockTransitKeyUseCase_List_Call {
	return &MockTransitKeyUseCase_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockTransitKeyUseCase_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockTransitKeyUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_List_Call) Return(transitKeys []*domain0.TransitKey, err error) *MockTransitKeyUseCase_List_Call {
	_c.Call.Return(transitKeys, err)
	return _c
}

func (_c *MockTransitKeyUseCase_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*domain0.TransitKey, error)) *MockTransitKeyUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockTransitKeyUseCase
func (_mock *MockTransitKeyUseCase) Rotate(ctx context.Context, name string, alg domain.Algorithm) (*domain0.TransitKey, error) {
	ret := _mock.Called(ctx, name, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *domain0.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) (*domain0.TransitKey, error)); ok {
		return returnFunc(ctx, name, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) *domain0.TransitKey); ok {
		r0 = returnFunc(ctx, name, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain0.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Algorithm) error); ok {
		r1 = returnFunc(ctx, name, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockTransitKeyUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - alg domain.Algorithm
func (_e *MockTransitKeyUseCase_Expecter) Rotate(ctx interface{}, name interface{}, alg interface{}) *MockTransitKeyUseCase_Rotate_Call {
	return &MockTransitKeyUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, name, alg)}
}

func (_c *MockTransitKeyUseCase_Rotate_Call) Run(run func(ctx context.Context, name string, alg domain.Algorithm)) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Rotate_Call) Return(transitKey *domain0.TransitKey, err error) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyUseCase_Rotate_Call) RunAndReturn(run func(ctx context.Context, name string, alg domain.Algorithm) (*domain0.TransitKey, error)) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}
