// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/transit/domain"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockTransitKeyRepository is an autogenerated mock type for the TransitKeyRepository type
type MockTransitKeyRepository struct {
	mock.Mock
}

type MockTransitKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitKeyRepository) EXPECT() *MockTransitKeyRepository_Expecter {
	return &MockTransitKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, transitKey
func (_m *MockTransitKeyRepository) Create(ctx context.Context, transitKey *domain.TransitKey) error {
	ret := _m.Called(ctx, transitKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TransitKey) error); ok {
		r0 = rf(ctx, transitKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransitKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransitKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKey *domain.TransitKey
func (_e *MockTransitKeyRepository_Expecter) Create(ctx interface{}, transitKey interface{}) *MockTransitKeyRepository_Create_Call {
	return &MockTransitKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, transitKey)}
}

func (_c *MockTransitKeyRepository_Create_Call) Run(run func(ctx context.Context, transitKey *domain.TransitKey)) *MockTransitKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TransitKey))
	})
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) Return(_a0 error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.TransitKey) error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, transitKeyID
func (_m *MockTransitKeyRepository) Delete(ctx context.Context, transitKeyID uuid.UUID) error {
	ret := _m.Called(ctx, transitKeyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, transitKeyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransitKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransitKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKeyID uuid.UUID
func (_e *MockTransitKeyRepository_Expecter) Delete(ctx interface{}, transitKeyID interface{}) *MockTransitKeyRepository_Delete_Call {
	return &MockTransitKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, transitKeyID)}
}

func (_c *MockTransitKeyRepository_Delete_Call) Run(run func(ctx context.Context, transitKeyID uuid.UUID)) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) Return(_a0 error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockTransitKeyRepository) GetByName(ctx context.Context, name string) (*domain.TransitKey, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.TransitKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.TransitKey, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.TransitKey); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransitKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTransitKeyRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransitKeyRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockTransitKeyRepository_GetByName_Call {
	return &MockTransitKeyRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTransitKeyRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) Return(_a0 *domain.TransitKey, _a1 error) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*domain.TransitKey, error)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNameAndVersion provides a mock function with given fields: ctx, name, version
func (_m *MockTransitKeyRepository) GetByNameAndVersion(ctx context.Context, name string, version uint) (*domain.TransitKey, error) {
	ret := _m.Called(ctx, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndVersion")
	}

	var r0 *domain.TransitKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.TransitKey, error)); ok {
		return rf(ctx, name, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) *domain.TransitKey); ok {
		r0 = rf(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransitKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyRepository_GetByNameAndVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNameAndVersion'
type MockTransitKeyRepository_GetByNameAndVersion_Call struct {
	*mock.Call
}

// GetByNameAndVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version uint
func (_e *MockTransitKeyRepository_Expecter) GetByNameAndVersion(ctx interface{}, name interface{}, version interface{}) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	return &MockTransitKeyRepository_GetByNameAndVersion_Call{Call: _e.mock.On("GetByNameAndVersion", ctx, name, version)}
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Run(run func(ctx context.Context, name string, version uint)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Return(_a0 *domain.TransitKey, _a1 error) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) RunAndReturn(run func(context.Context, string, uint) (*domain.TransitKey, error)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitKeyRepository creates a new instance of MockTransitKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitKeyRepository {
	mock := &MockTransitKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
