// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"

	transitdomain "github.com/allisson/secrets/internal/transit/domain"

	uuid "github.com/google/uuid"
)

// MockTransitKeyUseCase is an autogenerated mock type for the TransitKeyUseCase type
type MockTransitKeyUseCase struct {
	mock.Mock
}

type MockTransitKeyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitKeyUseCase) EXPECT() *MockTransitKeyUseCase_Expecter {
	return &MockTransitKeyUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, alg
func (_m *MockTransitKeyUseCase) Create(ctx context.Context, name string, alg domain.Algorithm) (*transitdomain.TransitKey, error) {
	ret := _m.Called(ctx, name, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *transitdomain.TransitKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) (*transitdomain.TransitKey, error)); ok {
		return rf(ctx, name, alg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) *transitdomain.TransitKey); ok {
		r0 = rf(ctx, name, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transitdomain.TransitKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Algorithm) error); ok {
		r1 = rf(ctx, name, alg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransitKeyUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - alg domain.Algorithm
func (_e *MockTransitKeyUseCase_Expecter) Create(ctx interface{}, name interface{}, alg interface{}) *MockTransitKeyUseCase_Create_Call {
	return &MockTransitKeyUseCase_Create_Call{Call: _e.mock.On("Create", ctx, name, alg)}
}

func (_c *MockTransitKeyUseCase_Create_Call) Run(run func(ctx context.Context, name string, alg domain.Algorithm)) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Algorithm))
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Create_Call) Return(_a0 *transitdomain.TransitKey, _a1 error) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyUseCase_Create_Call) RunAndReturn(run func(context.Context, string, domain.Algorithm) (*transitdomain.TransitKey, error)) *MockTransitKeyUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function with given fields: ctx, name, ciphertext
func (_m *MockTransitKeyUseCase) Decrypt(ctx context.Context, name string, ciphertext []byte) (*transitdomain.EncryptedBlob, error) {
	ret := _m.Called(ctx, name, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 *transitdomain.EncryptedBlob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (*transitdomain.EncryptedBlob, error)); ok {
		return rf(ctx, name, ciphertext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *transitdomain.EncryptedBlob); ok {
		r0 = rf(ctx, name, ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transitdomain.EncryptedBlob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, name, ciphertext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyUseCase_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockTransitKeyUseCase_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ciphertext []byte
func (_e *MockTransitKeyUseCase_Expecter) Decrypt(ctx interface{}, name interface{}, ciphertext interface{}) *MockTransitKeyUseCase_Decrypt_Call {
	return &MockTransitKeyUseCase_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, name, ciphertext)}
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) Run(run func(ctx context.Context, name string, ciphertext []byte)) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) Return(_a0 *transitdomain.EncryptedBlob, _a1 error) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyUseCase_Decrypt_Call) RunAndReturn(run func(context.Context, string, []byte) (*transitdomain.EncryptedBlob, error)) *MockTransitKeyUseCase_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, transitKeyID
func (_m *MockTransitKeyUseCase) Delete(ctx context.Context, transitKeyID uuid.UUID) error {
	ret := _m.Called(ctx, transitKeyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, transitKeyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransitKeyUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransitKeyUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKeyID uuid.UUID
func (_e *MockTransitKeyUseCase_Expecter) Delete(ctx interface{}, transitKeyID interface{}) *MockTransitKeyUseCase_Delete_Call {
	return &MockTransitKeyUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, transitKeyID)}
}

func (_c *MockTransitKeyUseCase_Delete_Call) Run(run func(ctx context.Context, transitKeyID uuid.UUID)) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Delete_Call) Return(_a0 error) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransitKeyUseCase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTransitKeyUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: ctx, name, plaintext
func (_m *MockTransitKeyUseCase) Encrypt(ctx context.Context, name string, plaintext []byte) (*transitdomain.EncryptedBlob, error) {
	ret := _m.Called(ctx, name, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *transitdomain.EncryptedBlob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (*transitdomain.EncryptedBlob, error)); ok {
		return rf(ctx, name, plaintext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *transitdomain.EncryptedBlob); ok {
		r0 = rf(ctx, name, plaintext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transitdomain.EncryptedBlob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, name, plaintext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyUseCase_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockTransitKeyUseCase_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - plaintext []byte
func (_e *MockTransitKeyUseCase_Expecter) Encrypt(ctx interface{}, name interface{}, plaintext interface{}) *MockTransitKeyUseCase_Encrypt_Call {
	return &MockTransitKeyUseCase_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, name, plaintext)}
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) Run(run func(ctx context.Context, name string, plaintext []byte)) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) Return(_a0 *transitdomain.EncryptedBlob, _a1 error) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyUseCase_Encrypt_Call) RunAndReturn(run func(context.Context, string, []byte) (*transitdomain.EncryptedBlob, error)) *MockTransitKeyUseCase_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, name, alg
func (_m *MockTransitKeyUseCase) Rotate(ctx context.Context, name string, alg domain.Algorithm) (*transitdomain.TransitKey, error) {
	ret := _m.Called(ctx, name, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *transitdomain.TransitKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) (*transitdomain.TransitKey, error)); ok {
		return rf(ctx, name, alg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Algorithm) *transitdomain.TransitKey); ok {
		r0 = rf(ctx, name, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transitdomain.TransitKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Algorithm) error); ok {
		r1 = rf(ctx, name, alg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransitKeyUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockTransitKeyUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - alg domain.Algorithm
func (_e *MockTransitKeyUseCase_Expecter) Rotate(ctx interface{}, name interface{}, alg interface{}) *MockTransitKeyUseCase_Rotate_Call {
	return &MockTransitKeyUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, name, alg)}
}

func (_c *MockTransitKeyUseCase_Rotate_Call) Run(run func(ctx context.Context, name string, alg domain.Algorithm)) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Algorithm))
	})
	return _c
}

func (_c *MockTransitKeyUseCase_Rotate_Call) Return(_a0 *transitdomain.TransitKey, _a1 error) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransitKeyUseCase_Rotate_Call) RunAndReturn(run func(context.Context, string, domain.Algorithm) (*transitdomain.TransitKey, error)) *MockTransitKeyUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransitKeyUseCase creates a new instance of MockTransitKeyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitKeyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitKeyUseCase {
	mock := &MockTransitKeyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
