// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockKekRepository is an autogenerated mock type for the KekRepository type
type MockKekRepository struct {
	mock.Mock
}

type MockKekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekRepository) EXPECT() *MockKekRepository_Expecter {
	return &MockKekRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, kek
func (_m *MockKekRepository) Create(ctx context.Context, kek *domain.Kek) error {
	ret := _m.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = rf(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKekRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Create(ctx interface{}, kek interface{}) *MockKekRepository_Create_Call {
	return &MockKekRepository_Create_Call{Call: _e.mock.On("Create", ctx, kek)}
}

func (_c *MockKekRepository_Create_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Kek))
	})
	return _c
}

func (_c *MockKekRepository_Create_Call) Return(_a0 error) *MockKekRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKekRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Kek) error) *MockKekRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockKekRepository) List(ctx context.Context) ([]*domain.Kek, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Kek
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Kek, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Kek); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Kek)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKekRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKekRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKekRepository_Expecter) List(ctx interface{}) *MockKekRepository_List_Call {
	return &MockKekRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockKekRepository_List_Call) Run(run func(ctx context.Context)) *MockKekRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockKekRepository_List_Call) Return(_a0 []*domain.Kek, _a1 error) *MockKekRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKekRepository_List_Call) RunAndReturn(run func(context.Context) ([]*domain.Kek, error)) *MockKekRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, kek
func (_m *MockKekRepository) Update(ctx context.Context, kek *domain.Kek) error {
	ret := _m.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = rf(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKekRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKekRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Update(ctx interface{}, kek interface{}) *MockKekRepository_Update_Call {
	return &MockKekRepository_Update_Call{Call: _e.mock.On("Update", ctx, kek)}
}

func (_c *MockKekRepository_Update_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Kek))
	})
	return _c
}

func (_c *MockKekRepository_Update_Call) Return(_a0 error) *MockKekRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKekRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Kek) error) *MockKekRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKekRepository creates a new instance of MockKekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekRepository {
	mock := &MockKekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
