// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockKekUseCase is an autogenerated mock type for the KekUseCase type
type MockKekUseCase struct {
	mock.Mock
}

type MockKekUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekUseCase) EXPECT() *MockKekUseCase_Expecter {
	return &MockKekUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, masterKeyChain, alg
func (_m *MockKekUseCase) Create(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _m.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = rf(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKekUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Create(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Create_Call {
	return &MockKekUseCase_Create_Call{Call: _e.mock.On("Create", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Create_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.MasterKeyChain), args[2].(domain.Algorithm))
	})
	return _c
}

func (_c *MockKekUseCase_Create_Call) Return(_a0 error) *MockKekUseCase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKekUseCase_Create_Call) RunAndReturn(run func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error) *MockKekUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, masterKeyChain, alg
func (_m *MockKekUseCase) Rotate(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _m.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = rf(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKekUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockKekUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Rotate(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Rotate_Call {
	return &MockKekUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Rotate_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.MasterKeyChain), args[2].(domain.Algorithm))
	})
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) Return(_a0 error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) RunAndReturn(run func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function with given fields: ctx, masterKeyChain
func (_m *MockKekUseCase) Unwrap(ctx context.Context, masterKeyChain *domain.MasterKeyChain) (*domain.KekChain, error) {
	ret := _m.Called(ctx, masterKeyChain)

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 *domain.KekChain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) (*domain.KekChain, error)); ok {
		return rf(ctx, masterKeyChain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) *domain.KekChain); ok {
		r0 = rf(ctx, masterKeyChain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KekChain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.MasterKeyChain) error); ok {
		r1 = rf(ctx, masterKeyChain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKekUseCase_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type MockKekUseCase_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
func (_e *MockKekUseCase_Expecter) Unwrap(ctx interface{}, masterKeyChain interface{}) *MockKekUseCase_Unwrap_Call {
	return &MockKekUseCase_Unwrap_Call{Call: _e.mock.On("Unwrap", ctx, masterKeyChain)}
}

func (_c *MockKekUseCase_Unwrap_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.MasterKeyChain))
	})
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) Return(_a0 *domain.KekChain, _a1 error) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) RunAndReturn(run func(context.Context, *domain.MasterKeyChain) (*domain.KekChain, error)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKekUseCase creates a new instance of MockKekUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekUseCase {
	mock := &MockKekUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
