// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKekRepository creates a new instance of MockKekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekRepository {
	mock := &MockKekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKekRepository is an autogenerated mock type for the KekRepository type
type MockKekRepository struct {
	mock.Mock
}

type MockKekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekRepository) EXPECT() *MockKekRepository_Expecter {
	return &MockKekRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) Create(ctx context.Context, kek *domain.Kek) error {
	ret := _mock.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = returnFunc(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Create(ctx interface{}, kek interface{}) *MockKekRepository_Create_Call {
	return &MockKekRepository_Create_Call{Call: _e.mock.On("Create", ctx, kek)}
}

func (_c *MockKekRepository_Create_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekRepository_Create_Call) Return(err error) *MockKekRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekRepository_Create_Call) RunAndReturn(run func(ctx context.Context, kek *domain.Kek) error) *MockKekRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) List(ctx context.Context) ([]*domain.Kek, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Kek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Kek, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Kek); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Kek)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKekRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKekRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKekRepository_Expecter) List(ctx interface{}) *MockKekRepository_List_Call {
	return &MockKekRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockKekRepository_List_Call) Run(run func(ctx context.Context)) *MockKekRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKekRepository_List_Call) Return(keks []*domain.Kek, err error) *MockKekRepository_List_Call {
	_c.Call.Return(keks, err)
	return _c
}

func (_c *MockKekRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Kek, error)) *MockKekRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) Update(ctx context.Context, kek *domain.Kek) error {
	ret := _mock.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = returnFunc(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKekRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Update(ctx interface{}, kek interface{}) *MockKekRepository_Update_Call {
	return &MockKekRepository_Update_Call{Call: _e.mock.On("Update", ctx, kek)}
}

func (_c *MockKekRepository_Update_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekRepository_Update_Call) Return(err error) *MockKekRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekRepository_Update_Call) RunAndReturn(run func(ctx context.Context, kek *domain.Kek) error) *MockKekRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKekUseCase creates a new instance of MockKekUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekUseCase {
	mock := &MockKekUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKekUseCase is an autogenerated mock type for the KekUseCase type
type MockKekUseCase struct {
	mock.Mock
}

type MockKekUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekUseCase) EXPECT() *MockKekUseCase_Expecter {
	return &MockKekUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Create(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Create(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Create_Call {
	return &MockKekUseCase_Create_Call{Call: _e.mock.On("Create", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Create_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Create_Call) Return(err error) *MockKekUseCase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error) *MockKekUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Rotate(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockKekUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Rotate(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Rotate_Call {
	return &MockKekUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Rotate_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) Return(err error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Unwrap(ctx context.Context, masterKeyChain *domain.MasterKeyChain) (*domain.KekChain, error) {
	ret := _mock.Called(ctx, masterKeyChain)

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 *domain.KekChain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) (*domain.KekChain, error)); ok {
		return returnFunc(ctx, masterKeyChain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) *domain.KekChain); ok {
		r0 = returnFunc(ctx, masterKeyChain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KekChain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.MasterKeyChain) error); ok {
		r1 = returnFunc(ctx, masterKeyChain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKekUseCase_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type MockKekUseCase_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
func (_e *MockKekUseCase_Expecter) Unwrap(ctx interface{}, masterKeyChain interface{}) *MockKekUseCase_Unwrap_Call {
	return &MockKekUseCase_Unwrap_Call{Call: _e.mock.On("Unwrap", ctx, masterKeyChain)}
}

func (_c *MockKekUseCase_Unwrap_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) Return(kekChain *domain.KekChain, err error) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(kekChain, err)
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain) (*domain.KekChain, error)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}
