// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/allisson/secrets/internal/crypto/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKekRepository creates a new instance of MockKekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekRepository {
	mock := &MockKekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKekRepository is an autogenerated mock type for the KekRepository type
type MockKekRepository struct {
	mock.Mock
}

type MockKekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekRepository) EXPECT() *MockKekRepository_Expecter {
	return &MockKekRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) Create(ctx context.Context, kek *domain.Kek) error {
	ret := _mock.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = returnFunc(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Create(ctx interface{}, kek interface{}) *MockKekRepository_Create_Call {
	return &MockKekRepository_Create_Call{Call: _e.mock.On("Create", ctx, kek)}
}

func (_c *MockKekRepository_Create_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekRepository_Create_Call) Return(err error) *MockKekRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekRepository_Create_Call) RunAndReturn(run func(ctx context.Context, kek *domain.Kek) error) *MockKekRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) List(ctx context.Context) ([]*domain.Kek, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Kek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Kek, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Kek); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Kek)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKekRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKekRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKekRepository_Expecter) List(ctx interface{}) *MockKekRepository_List_Call {
	return &MockKekRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockKekRepository_List_Call) Run(run func(ctx context.Context)) *MockKekRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKekRepository_List_Call) Return(keks []*domain.Kek, err error) *MockKekRepository_List_Call {
	_c.Call.Return(keks, err)
	return _c
}

func (_c *MockKekRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Kek, error)) *MockKekRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockKekRepository
func (_mock *MockKekRepository) Update(ctx context.Context, kek *domain.Kek) error {
	ret := _mock.Called(ctx, kek)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Kek) error); ok {
		r0 = returnFunc(ctx, kek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockKekRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - kek *domain.Kek
func (_e *MockKekRepository_Expecter) Update(ctx interface{}, kek interface{}) *MockKekRepository_Update_Call {
	return &MockKekRepository_Update_Call{Call: _e.mock.On("Update", ctx, kek)}
}

func (_c *MockKekRepository_Update_Call) Run(run func(ctx context.Context, kek *domain.Kek)) *MockKekRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekRepository_Update_Call) Return(err error) *MockKekRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekRepository_Update_Call) RunAndReturn(run func(ctx context.Context, kek *domain.Kek) error) *MockKekRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKekUseCase creates a new instance of MockKekUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekUseCase {
	mock := &MockKekUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKekUseCase is an autogenerated mock type for the KekUseCase type
type MockKekUseCase struct {
	mock.Mock
}

type MockKekUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekUseCase) EXPECT() *MockKekUseCase_Expecter {
	return &MockKekUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Create(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Create(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Create_Call {
	return &MockKekUseCase_Create_Call{Call: _e.mock.On("Create", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Create_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Create_Call) Return(err error) *MockKekUseCase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error) *MockKekUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Rotate(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain, domain.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockKekUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
//   - alg domain.Algorithm
func (_e *MockKekUseCase_Expecter) Rotate(ctx interface{}, masterKeyChain interface{}, alg interface{}) *MockKekUseCase_Rotate_Call {
	return &MockKekUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Rotate_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm)) *MockKekUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		var arg2 domain.Algorithm
		if args[2] != nil {
			arg2 = args[2].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) Return(err error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain, alg domain.Algorithm) error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Unwrap(ctx context.Context, masterKeyChain *domain.MasterKeyChain) (*domain.KekChain, error) {
	ret := _mock.Called(ctx, masterKeyChain)

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 *domain.KekChain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) (*domain.KekChain, error)); ok {
		return returnFunc(ctx, masterKeyChain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MasterKeyChain) *domain.KekChain); ok {
		r0 = returnFunc(ctx, masterKeyChain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.KekChain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.MasterKeyChain) error); ok {
		r1 = returnFunc(ctx, masterKeyChain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKekUseCase_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type MockKekUseCase_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *domain.MasterKeyChain
func (_e *MockKekUseCase_Expecter) Unwrap(ctx interface{}, masterKeyChain interface{}) *MockKekUseCase_Unwrap_Call {
	return &MockKekUseCase_Unwrap_Call{Call: _e.mock.On("Unwrap", ctx, masterKeyChain)}
}

func (_c *MockKekUseCase_Unwrap_Call) Run(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKeyChain)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) Return(kekChain *domain.KekChain, err error) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(kekChain, err)
	return _c
}

func (_c *MockKekUseCase_Unwrap_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *domain.MasterKeyChain) (*domain.KekChain, error)) *MockKekUseCase_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDekRepository creates a new instance of MockDekRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDekRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDekRepository {
	mock := &MockDekRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDekRepository is an autogenerated mock type for the DekRepository type
type MockDekRepository struct {
	mock.Mock
}

type MockDekRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDekRepository) EXPECT() *MockDekRepository_Expecter {
	return &MockDekRepository_Expecter{mock: &_m.Mock}
}

// GetBatchNotKekID provides a mock function for the type MockDekRepository
func (_mock *MockDekRepository) GetBatchNotKekID(ctx context.Context, kekID uuid.UUID, limit int) ([]*domain.Dek, error) {
	ret := _mock.Called(ctx, kekID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBatchNotKekID")
	}

	var r0 []*domain.Dek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*domain.Dek, error)); ok {
		return returnFunc(ctx, kekID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*domain.Dek); ok {
		r0 = returnFunc(ctx, kekID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Dek)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, kekID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDekRepository_GetBatchNotKekID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatchNotKekID'
type MockDekRepository_GetBatchNotKekID_Call struct {
	*mock.Call
}

// GetBatchNotKekID is a helper method to define mock.On call
//   - ctx context.Context
//   - kekID uuid.UUID
//   - limit int
func (_e *MockDekRepository_Expecter) GetBatchNotKekID(ctx interface{}, kekID interface{}, limit interface{}) *MockDekRepository_GetBatchNotKekID_Call {
	return &MockDekRepository_GetBatchNotKekID_Call{Call: _e.mock.On("GetBatchNotKekID", ctx, kekID, limit)}
}

func (_c *MockDekRepository_GetBatchNotKekID_Call) Run(run func(ctx context.Context, kekID uuid.UUID, limit int)) *MockDekRepository_GetBatchNotKekID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDekRepository_GetBatchNotKekID_Call) Return(deks []*domain.Dek, err error) *MockDekRepository_GetBatchNotKekID_Call {
	_c.Call.Return(deks, err)
	return _c
}

func (_c *MockDekRepository_GetBatchNotKekID_Call) RunAndReturn(run func(ctx context.Context, kekID uuid.UUID, limit int) ([]*domain.Dek, error)) *MockDekRepository_GetBatchNotKekID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDekRepository
func (_mock *MockDekRepository) Update(ctx context.Context, dek *domain.Dek) error {
	ret := _mock.Called(ctx, dek)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Dek) error); ok {
		r0 = returnFunc(ctx, dek)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDekRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDekRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dek *domain.Dek
func (_e *MockDekRepository_Expecter) Update(ctx interface{}, dek interface{}) *MockDekRepository_Update_Call {
	return &MockDekRepository_Update_Call{Call: _e.mock.On("Update", ctx, dek)}
}

func (_c *MockDekRepository_Update_Call) Run(run func(ctx context.Context, dek *domain.Dek)) *MockDekRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Dek
		if args[1] != nil {
			arg1 = args[1].(*domain.Dek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDekRepository_Update_Call) Return(err error) *MockDekRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDekRepository_Update_Call) RunAndReturn(run func(ctx context.Context, dek *domain.Dek) error) *MockDekRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDekUseCase creates a new instance of MockDekUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDekUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDekUseCase {
	mock := &MockDekUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDekUseCase is an autogenerated mock type for the DekUseCase type
type MockDekUseCase struct {
	mock.Mock
}

type MockDekUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDekUseCase) EXPECT() *MockDekUseCase_Expecter {
	return &MockDekUseCase_Expecter{mock: &_m.Mock}
}

// Rewrap provides a mock function for the type MockDekUseCase
func (_mock *MockDekUseCase) Rewrap(ctx context.Context, kekChain *domain.KekChain, newKekID uuid.UUID, batchSize int) (int, error) {
	ret := _mock.Called(ctx, kekChain, newKekID, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for Rewrap")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.KekChain, uuid.UUID, int) (int, error)); ok {
		return returnFunc(ctx, kekChain, newKekID, batchSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.KekChain, uuid.UUID, int) int); ok {
		r0 = returnFunc(ctx, kekChain, newKekID, batchSize)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.KekChain, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, kekChain, newKekID, batchSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDekUseCase_Rewrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rewrap'
type MockDekUseCase_Rewrap_Call struct {
	*mock.Call
}

// Rewrap is a helper method to define mock.On call
//   - ctx context.Context
//   - kekChain *domain.KekChain
//   - newKekID uuid.UUID
//   - batchSize int
func (_e *MockDekUseCase_Expecter) Rewrap(ctx interface{}, kekChain interface{}, newKekID interface{}, batchSize interface{}) *MockDekUseCase_Rewrap_Call {
	return &MockDekUseCase_Rewrap_Call{Call: _e.mock.On("Rewrap", ctx, kekChain, newKekID, batchSize)}
}

func (_c *MockDekUseCase_Rewrap_Call) Run(run func(ctx context.Context, kekChain *domain.KekChain, newKekID uuid.UUID, batchSize int)) *MockDekUseCase_Rewrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.KekChain
		if args[1] != nil {
			arg1 = args[1].(*domain.KekChain)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDekUseCase_Rewrap_Call) Return(n int, err error) *MockDekUseCase_Rewrap_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDekUseCase_Rewrap_Call) RunAndReturn(run func(ctx context.Context, kekChain *domain.KekChain, newKekID uuid.UUID, batchSize int) (int, error)) *MockDekUseCase_Rewrap_Call {
	_c.Call.Return(run)
	return _c
}
