// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/allisson/secrets/internal/keyring"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKekUseCase creates a new instance of MockKekUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKekUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKekUseCase {
	mock := &MockKekUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKekUseCase is an autogenerated mock type for the KekUseCase type
type MockKekUseCase struct {
	mock.Mock
}

type MockKekUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKekUseCase) EXPECT() *MockKekUseCase_Expecter {
	return &MockKekUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Create(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *keyring.MasterKeyChain, keyring.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockKekUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *keyring.MasterKeyChain
//   - alg keyring.Algorithm
func (_e *MockKekUseCase_Expecter) Create(ctx any, masterKeyChain any, alg any) *MockKekUseCase_Create_Call {
	return &MockKekUseCase_Create_Call{Call: _e.mock.On("Create", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Create_Call) Run(run func(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm)) *MockKekUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *keyring.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*keyring.MasterKeyChain)
		}
		var arg2 keyring.Algorithm
		if args[2] != nil {
			arg2 = args[2].(keyring.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Create_Call) Return(err error) *MockKekUseCase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm) error) *MockKekUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type MockKekUseCase
func (_mock *MockKekUseCase) Rotate(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm) error {
	ret := _mock.Called(ctx, masterKeyChain, alg)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *keyring.MasterKeyChain, keyring.Algorithm) error); ok {
		r0 = returnFunc(ctx, masterKeyChain, alg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKekUseCase_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockKekUseCase_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - masterKeyChain *keyring.MasterKeyChain
//   - alg keyring.Algorithm
func (_e *MockKekUseCase_Expecter) Rotate(ctx any, masterKeyChain any, alg any) *MockKekUseCase_Rotate_Call {
	return &MockKekUseCase_Rotate_Call{Call: _e.mock.On("Rotate", ctx, masterKeyChain, alg)}
}

func (_c *MockKekUseCase_Rotate_Call) Run(run func(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm)) *MockKekUseCase_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *keyring.MasterKeyChain
		if args[1] != nil {
			arg1 = args[1].(*keyring.MasterKeyChain)
		}
		var arg2 keyring.Algorithm
		if args[2] != nil {
			arg2 = args[2].(keyring.Algorithm)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) Return(err error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKekUseCase_Rotate_Call) RunAndReturn(run func(ctx context.Context, masterKeyChain *keyring.MasterKeyChain, alg keyring.Algorithm) error) *MockKekUseCase_Rotate_Call {
	_c.Call.Return(run)
	return _c
}
