// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, auditLog
func (_m *MockAuditLogRepository) Create(ctx context.Context, auditLog *domain.AuditLog) error {
	ret := _m.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = rf(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auditLog *domain.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx interface{}, auditLog interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, auditLog)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, auditLog *domain.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(_a0 error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
