// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, auditLog
func (_m *MockAuditLogRepository) Create(ctx context.Context, auditLog *domain.AuditLog) error {
	ret := _m.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = rf(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auditLog *domain.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx interface{}, auditLog interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, auditLog)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, auditLog *domain.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuditLog))
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(_a0 error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockAuditLogRepository) List(ctx context.Context, offset int, limit int) ([]*domain.AuditLog, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.AuditLog, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.AuditLog); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockAuditLogRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockAuditLogRepository_List_Call {
	return &MockAuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockAuditLogRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockAuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAuditLogRepository_List_Call) Return(_a0 []*domain.AuditLog, _a1 error) *MockAuditLogRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuditLogRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*domain.AuditLog, error)) *MockAuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
