// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuditLogUseCase is an autogenerated mock type for the AuditLogUseCase type
type MockAuditLogUseCase struct {
	mock.Mock
}

type MockAuditLogUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogUseCase) EXPECT() *MockAuditLogUseCase_Expecter {
	return &MockAuditLogUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, requestID, clientID, capability, path, metadata
func (_m *MockAuditLogUseCase) Create(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]interface{}) error {
	ret := _m.Called(ctx, requestID, clientID, capability, path, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.Capability, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, requestID, clientID, capability, path, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - clientID uuid.UUID
//   - capability domain.Capability
//   - path string
//   - metadata map[string]interface{}
func (_e *MockAuditLogUseCase_Expecter) Create(ctx interface{}, requestID interface{}, clientID interface{}, capability interface{}, path interface{}, metadata interface{}) *MockAuditLogUseCase_Create_Call {
	return &MockAuditLogUseCase_Create_Call{Call: _e.mock.On("Create", ctx, requestID, clientID, capability, path, metadata)}
}

func (_c *MockAuditLogUseCase_Create_Call) Run(run func(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]interface{})) *MockAuditLogUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.Capability), args[4].(string), args[5].(map[string]interface{}))
	})
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) Return(_a0 error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.Capability, string, map[string]interface{}) error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogUseCase creates a new instance of MockAuditLogUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogUseCase {
	mock := &MockAuditLogUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
