// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockClientUseCase is an autogenerated mock type for the ClientUseCase type
type MockClientUseCase struct {
	mock.Mock
}

type MockClientUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientUseCase) EXPECT() *MockClientUseCase_Expecter {
	return &MockClientUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createClientInput
func (_m *MockClientUseCase) Create(ctx context.Context, createClientInput *domain.CreateClientInput) (*domain.CreateClientOutput, error) {
	ret := _m.Called(ctx, createClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.CreateClientOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) (*domain.CreateClientOutput, error)); ok {
		return rf(ctx, createClientInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) *domain.CreateClientOutput); ok {
		r0 = rf(ctx, createClientInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateClientOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateClientInput) error); ok {
		r1 = rf(ctx, createClientInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createClientInput *domain.CreateClientInput
func (_e *MockClientUseCase_Expecter) Create(ctx interface{}, createClientInput interface{}) *MockClientUseCase_Create_Call {
	return &MockClientUseCase_Create_Call{Call: _e.mock.On("Create", ctx, createClientInput)}
}

func (_c *MockClientUseCase_Create_Call) Run(run func(ctx context.Context, createClientInput *domain.CreateClientInput)) *MockClientUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CreateClientInput))
	})
	return _c
}

func (_c *MockClientUseCase_Create_Call) Return(_a0 *domain.CreateClientOutput, _a1 error) *MockClientUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientUseCase_Create_Call) RunAndReturn(run func(context.Context, *domain.CreateClientInput) (*domain.CreateClientOutput, error)) *MockClientUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, clientID
func (_m *MockClientUseCase) Delete(ctx context.Context, clientID uuid.UUID) error {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClientUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Delete(ctx interface{}, clientID interface{}) *MockClientUseCase_Delete_Call {
	return &MockClientUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, clientID)}
}

func (_c *MockClientUseCase_Delete_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockClientUseCase_Delete_Call) Return(_a0 error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientUseCase_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, clientID
func (_m *MockClientUseCase) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Get(ctx interface{}, clientID interface{}) *MockClientUseCase_Get_Call {
	return &MockClientUseCase_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientUseCase_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockClientUseCase_Get_Call) Return(_a0 *domain.Client, _a1 error) *MockClientUseCase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientUseCase_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Client, error)) *MockClientUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, clientID, updateClientInput
func (_m *MockClientUseCase) Update(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput) error {
	ret := _m.Called(ctx, clientID, updateClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateClientInput) error); ok {
		r0 = rf(ctx, clientID, updateClientInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - updateClientInput *domain.UpdateClientInput
func (_e *MockClientUseCase_Expecter) Update(ctx interface{}, clientID interface{}, updateClientInput interface{}) *MockClientUseCase_Update_Call {
	return &MockClientUseCase_Update_Call{Call: _e.mock.On("Update", ctx, clientID, updateClientInput)}
}

func (_c *MockClientUseCase_Update_Call) Run(run func(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput)) *MockClientUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.UpdateClientInput))
	})
	return _c
}

func (_c *MockClientUseCase_Update_Call) Return(_a0 error) *MockClientUseCase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientUseCase_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.UpdateClientInput) error) *MockClientUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientUseCase creates a new instance of MockClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientUseCase {
	mock := &MockClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
