// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, client
func (_m *MockClientRepository) Create(ctx context.Context, client *domain.Client) error {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Create(ctx interface{}, client interface{}) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, client)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Client))
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(_a0 error) *MockClientRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Client) error) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, clientID
func (_m *MockClientRepository) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = rf(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientRepository_Expecter) Get(ctx interface{}, clientID interface{}) *MockClientRepository_Get_Call {
	return &MockClientRepository_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientRepository_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockClientRepository_Get_Call) Return(_a0 *domain.Client, _a1 error) *MockClientRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Client, error)) *MockClientRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockClientRepository) List(ctx context.Context, offset int, limit int) ([]*domain.Client, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Client, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Client); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockClientRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockClientRepository_List_Call {
	return &MockClientRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockClientRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockClientRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockClientRepository_List_Call) Return(_a0 []*domain.Client, _a1 error) *MockClientRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*domain.Client, error)) *MockClientRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, client
func (_m *MockClientRepository) Update(ctx context.Context, client *domain.Client) error {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Update(ctx interface{}, client interface{}) *MockClientRepository_Update_Call {
	return &MockClientRepository_Update_Call{Call: _e.mock.On("Update", ctx, client)}
}

func (_c *MockClientRepository_Update_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Client))
	})
	return _c
}

func (_c *MockClientRepository_Update_Call) Return(_a0 error) *MockClientRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Client) error) *MockClientRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
