// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/auth/domain"
	"github.com/allisson/secrets/internal/auth/usecase"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientUseCase creates a new instance of MockClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientUseCase {
	mock := &MockClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientUseCase is an autogenerated mock type for the ClientUseCase type
type MockClientUseCase struct {
	mock.Mock
}

type MockClientUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientUseCase) EXPECT() *MockClientUseCase_Expecter {
	return &MockClientUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Create(ctx context.Context, createClientInput *domain.CreateClientInput) (*domain.CreateClientOutput, error) {
	ret := _mock.Called(ctx, createClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.CreateClientOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) (*domain.CreateClientOutput, error)); ok {
		return returnFunc(ctx, createClientInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) *domain.CreateClientOutput); ok {
		r0 = returnFunc(ctx, createClientInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateClientOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateClientInput) error); ok {
		r1 = returnFunc(ctx, createClientInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createClientInput *domain.CreateClientInput
func (_e *MockClientUseCase_Expecter) Create(ctx any, createClientInput any) *MockClientUseCase_Create_Call {
	return &MockClientUseCase_Create_Call{Call: _e.mock.On("Create", ctx, createClientInput)}
}

func (_c *MockClientUseCase_Create_Call) Run(run func(ctx context.Context, createClientInput *domain.CreateClientInput)) *MockClientUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateClientInput
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateClientInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Create_Call) Return(createClientOutput *domain.CreateClientOutput, err error) *MockClientUseCase_Create_Call {
	_c.Call.Return(createClientOutput, err)
	return _c
}

func (_c *MockClientUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, createClientInput *domain.CreateClientInput) (*domain.CreateClientOutput, error)) *MockClientUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Delete(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClientUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Delete(ctx any, clientID any) *MockClientUseCase_Delete_Call {
	return &MockClientUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, clientID)}
}

func (_c *MockClientUseCase_Delete_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Delete_Call) Return(err error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Get(ctx any, clientID any) *MockClientUseCase_Get_Call {
	return &MockClientUseCase_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientUseCase_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Get_Call) Return(client *domain.Client, err error) *MockClientUseCase_Get_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) (*domain.Client, error)) *MockClientUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) ListCursor(ctx context.Context, afterID *uuid.UUID, limit int) ([]*domain.Client, error) {
	ret := _mock.Called(ctx, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int) ([]*domain.Client, error)); ok {
		return returnFunc(ctx, afterID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int) []*domain.Client); ok {
		r0 = returnFunc(ctx, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockClientUseCase_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID *uuid.UUID
//   - limit int
func (_e *MockClientUseCase_Expecter) ListCursor(ctx any, afterID any, limit any) *MockClientUseCase_ListCursor_Call {
	return &MockClientUseCase_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterID, limit)}
}

func (_c *MockClientUseCase_ListCursor_Call) Run(run func(ctx context.Context, afterID *uuid.UUID, limit int)) *MockClientUseCase_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientUseCase_ListCursor_Call) Return(clients []*domain.Client, err error) *MockClientUseCase_ListCursor_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockClientUseCase_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterID *uuid.UUID, limit int) ([]*domain.Client, error)) *MockClientUseCase_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeTokens provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) RevokeTokens(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_RevokeTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeTokens'
type MockClientUseCase_RevokeTokens_Call struct {
	*mock.Call
}

// RevokeTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) RevokeTokens(ctx any, clientID any) *MockClientUseCase_RevokeTokens_Call {
	return &MockClientUseCase_RevokeTokens_Call{Call: _e.mock.On("RevokeTokens", ctx, clientID)}
}

func (_c *MockClientUseCase_RevokeTokens_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_RevokeTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_RevokeTokens_Call) Return(err error) *MockClientUseCase_RevokeTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_RevokeTokens_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientUseCase_RevokeTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RotateSecret provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) RotateSecret(ctx context.Context, clientID uuid.UUID) (*domain.CreateClientOutput, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RotateSecret")
	}

	var r0 *domain.CreateClientOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.CreateClientOutput, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.CreateClientOutput); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateClientOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_RotateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSecret'
type MockClientUseCase_RotateSecret_Call struct {
	*mock.Call
}

// RotateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) RotateSecret(ctx any, clientID any) *MockClientUseCase_RotateSecret_Call {
	return &MockClientUseCase_RotateSecret_Call{Call: _e.mock.On("RotateSecret", ctx, clientID)}
}

func (_c *MockClientUseCase_RotateSecret_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_RotateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_RotateSecret_Call) Return(createClientOutput *domain.CreateClientOutput, err error) *MockClientUseCase_RotateSecret_Call {
	_c.Call.Return(createClientOutput, err)
	return _c
}

func (_c *MockClientUseCase_RotateSecret_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) (*domain.CreateClientOutput, error)) *MockClientUseCase_RotateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Unlock(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockClientUseCase_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Unlock(ctx any, clientID any) *MockClientUseCase_Unlock_Call {
	return &MockClientUseCase_Unlock_Call{Call: _e.mock.On("Unlock", ctx, clientID)}
}

func (_c *MockClientUseCase_Unlock_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Unlock_Call) Return(err error) *MockClientUseCase_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Unlock_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientUseCase_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Update(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput) error {
	ret := _mock.Called(ctx, clientID, updateClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateClientInput) error); ok {
		r0 = returnFunc(ctx, clientID, updateClientInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - updateClientInput *domain.UpdateClientInput
func (_e *MockClientUseCase_Expecter) Update(ctx any, clientID any, updateClientInput any) *MockClientUseCase_Update_Call {
	return &MockClientUseCase_Update_Call{Call: _e.mock.On("Update", ctx, clientID, updateClientInput)}
}

func (_c *MockClientUseCase_Update_Call) Run(run func(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput)) *MockClientUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.UpdateClientInput
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateClientInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Update_Call) Return(err error) *MockClientUseCase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput) error) *MockClientUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenUseCase creates a new instance of MockTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUseCase {
	mock := &MockTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenUseCase is an autogenerated mock type for the TokenUseCase type
type MockTokenUseCase struct {
	mock.Mock
}

type MockTokenUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenUseCase) EXPECT() *MockTokenUseCase_Expecter {
	return &MockTokenUseCase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) Authenticate(ctx context.Context, rawToken string) (*domain.Client, error) {
	ret := _mock.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Client, error)); ok {
		return returnFunc(ctx, rawToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Client); ok {
		r0 = returnFunc(ctx, rawToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUseCase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockTokenUseCase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
func (_e *MockTokenUseCase_Expecter) Authenticate(ctx any, rawToken any) *MockTokenUseCase_Authenticate_Call {
	return &MockTokenUseCase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, rawToken)}
}

func (_c *MockTokenUseCase_Authenticate_Call) Run(run func(ctx context.Context, rawToken string)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) Return(client *domain.Client, err error) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) RunAndReturn(run func(ctx context.Context, rawToken string) (*domain.Client, error)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) Issue(ctx context.Context, issueTokenInput *domain.IssueTokenInput) (*domain.IssueTokenOutput, error) {
	ret := _mock.Called(ctx, issueTokenInput)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *domain.IssueTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)); ok {
		return returnFunc(ctx, issueTokenInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) *domain.IssueTokenOutput); ok {
		r0 = returnFunc(ctx, issueTokenInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IssueTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.IssueTokenInput) error); ok {
		r1 = returnFunc(ctx, issueTokenInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUseCase_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenUseCase_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - issueTokenInput *domain.IssueTokenInput
func (_e *MockTokenUseCase_Expecter) Issue(ctx any, issueTokenInput any) *MockTokenUseCase_Issue_Call {
	return &MockTokenUseCase_Issue_Call{Call: _e.mock.On("Issue", ctx, issueTokenInput)}
}

func (_c *MockTokenUseCase_Issue_Call) Run(run func(ctx context.Context, issueTokenInput *domain.IssueTokenInput)) *MockTokenUseCase_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.IssueTokenInput
		if args[1] != nil {
			arg1 = args[1].(*domain.IssueTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) Return(issueTokenOutput *domain.IssueTokenOutput, err error) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(issueTokenOutput, err)
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) RunAndReturn(run func(ctx context.Context, issueTokenInput *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeExpiredAndRevoked provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) PurgeExpiredAndRevoked(ctx context.Context, days int) (int64, error) {
	ret := _mock.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for PurgeExpiredAndRevoked")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, days)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, days)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, days)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUseCase_PurgeExpiredAndRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeExpiredAndRevoked'
type MockTokenUseCase_PurgeExpiredAndRevoked_Call struct {
	*mock.Call
}

// PurgeExpiredAndRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - days int
func (_e *MockTokenUseCase_Expecter) PurgeExpiredAndRevoked(ctx any, days any) *MockTokenUseCase_PurgeExpiredAndRevoked_Call {
	return &MockTokenUseCase_PurgeExpiredAndRevoked_Call{Call: _e.mock.On("PurgeExpiredAndRevoked", ctx, days)}
}

func (_c *MockTokenUseCase_PurgeExpiredAndRevoked_Call) Run(run func(ctx context.Context, days int)) *MockTokenUseCase_PurgeExpiredAndRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_PurgeExpiredAndRevoked_Call) Return(n int64, err error) *MockTokenUseCase_PurgeExpiredAndRevoked_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTokenUseCase_PurgeExpiredAndRevoked_Call) RunAndReturn(run func(ctx context.Context, days int) (int64, error)) *MockTokenUseCase_PurgeExpiredAndRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) Revoke(ctx context.Context, rawToken string) error {
	ret := _mock.Called(ctx, rawToken)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, rawToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenUseCase_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenUseCase_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - rawToken string
func (_e *MockTokenUseCase_Expecter) Revoke(ctx any, rawToken any) *MockTokenUseCase_Revoke_Call {
	return &MockTokenUseCase_Revoke_Call{Call: _e.mock.On("Revoke", ctx, rawToken)}
}

func (_c *MockTokenUseCase_Revoke_Call) Run(run func(ctx context.Context, rawToken string)) *MockTokenUseCase_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_Revoke_Call) Return(err error) *MockTokenUseCase_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenUseCase_Revoke_Call) RunAndReturn(run func(ctx context.Context, rawToken string) error) *MockTokenUseCase_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogUseCase creates a new instance of MockAuditLogUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogUseCase {
	mock := &MockAuditLogUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogUseCase is an autogenerated mock type for the AuditLogUseCase type
type MockAuditLogUseCase struct {
	mock.Mock
}

type MockAuditLogUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogUseCase) EXPECT() *MockAuditLogUseCase_Expecter {
	return &MockAuditLogUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) Create(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any) error {
	ret := _mock.Called(ctx, requestID, clientID, capability, path, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.Capability, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, requestID, clientID, capability, path, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - clientID uuid.UUID
//   - capability domain.Capability
//   - path string
//   - metadata map[string]any
func (_e *MockAuditLogUseCase_Expecter) Create(ctx any, requestID any, clientID any, capability any, path any, metadata any) *MockAuditLogUseCase_Create_Call {
	return &MockAuditLogUseCase_Create_Call{Call: _e.mock.On("Create", ctx, requestID, clientID, capability, path, metadata)}
}

func (_c *MockAuditLogUseCase_Create_Call) Run(run func(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any)) *MockAuditLogUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 domain.Capability
		if args[3] != nil {
			arg3 = args[3].(domain.Capability)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]any
		if args[5] != nil {
			arg5 = args[5].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) Return(err error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any) error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) DeleteOlderThan(ctx context.Context, days int, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, days, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (int64, error)); ok {
		return returnFunc(ctx, days, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) int64); ok {
		r0 = returnFunc(ctx, days, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, days, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogUseCase_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockAuditLogUseCase_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - days int
//   - dryRun bool
func (_e *MockAuditLogUseCase_Expecter) DeleteOlderThan(ctx any, days any, dryRun any) *MockAuditLogUseCase_DeleteOlderThan_Call {
	return &MockAuditLogUseCase_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, days, dryRun)}
}

func (_c *MockAuditLogUseCase_DeleteOlderThan_Call) Run(run func(ctx context.Context, days int, dryRun bool)) *MockAuditLogUseCase_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_DeleteOlderThan_Call) Return(n int64, err error) *MockAuditLogUseCase_DeleteOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuditLogUseCase_DeleteOlderThan_Call) RunAndReturn(run func(ctx context.Context, days int, dryRun bool) (int64, error)) *MockAuditLogUseCase_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) ListCursor(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID) ([]*domain.AuditLog, error) {
	ret := _mock.Called(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) ([]*domain.AuditLog, error)); ok {
		return returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) []*domain.AuditLog); ok {
		r0 = returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogUseCase_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockAuditLogUseCase_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID *uuid.UUID
//   - limit int
//   - createdAtFrom *time.Time
//   - createdAtTo *time.Time
//   - clientID *uuid.UUID
func (_e *MockAuditLogUseCase_Expecter) ListCursor(ctx any, afterID any, limit any, createdAtFrom any, createdAtTo any, clientID any) *MockAuditLogUseCase_ListCursor_Call {
	return &MockAuditLogUseCase_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)}
}

func (_c *MockAuditLogUseCase_ListCursor_Call) Run(run func(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID)) *MockAuditLogUseCase_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 *uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_ListCursor_Call) Return(auditLogs []*domain.AuditLog, err error) *MockAuditLogUseCase_ListCursor_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockAuditLogUseCase_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID) ([]*domain.AuditLog, error)) *MockAuditLogUseCase_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyBatch provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) VerifyBatch(ctx context.Context, startTime time.Time, endTime time.Time) (*usecase.VerificationReport, error) {
	ret := _mock.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for VerifyBatch")
	}

	var r0 *usecase.VerificationReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (*usecase.VerificationReport, error)); ok {
		return returnFunc(ctx, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) *usecase.VerificationReport); ok {
		r0 = returnFunc(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.VerificationReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogUseCase_VerifyBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyBatch'
type MockAuditLogUseCase_VerifyBatch_Call struct {
	*mock.Call
}

// VerifyBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockAuditLogUseCase_Expecter) VerifyBatch(ctx any, startTime any, endTime any) *MockAuditLogUseCase_VerifyBatch_Call {
	return &MockAuditLogUseCase_VerifyBatch_Call{Call: _e.mock.On("VerifyBatch", ctx, startTime, endTime)}
}

func (_c *MockAuditLogUseCase_VerifyBatch_Call) Run(run func(ctx context.Context, startTime time.Time, endTime time.Time)) *MockAuditLogUseCase_VerifyBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_VerifyBatch_Call) Return(verificationReport *usecase.VerificationReport, err error) *MockAuditLogUseCase_VerifyBatch_Call {
	_c.Call.Return(verificationReport, err)
	return _c
}

func (_c *MockAuditLogUseCase_VerifyBatch_Call) RunAndReturn(run func(ctx context.Context, startTime time.Time, endTime time.Time) (*usecase.VerificationReport, error)) *MockAuditLogUseCase_VerifyBatch_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyIntegrity provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) VerifyIntegrity(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIntegrity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogUseCase_VerifyIntegrity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIntegrity'
type MockAuditLogUseCase_VerifyIntegrity_Call struct {
	*mock.Call
}

// VerifyIntegrity is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditLogUseCase_Expecter) VerifyIntegrity(ctx any, id any) *MockAuditLogUseCase_VerifyIntegrity_Call {
	return &MockAuditLogUseCase_VerifyIntegrity_Call{Call: _e.mock.On("VerifyIntegrity", ctx, id)}
}

func (_c *MockAuditLogUseCase_VerifyIntegrity_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditLogUseCase_VerifyIntegrity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_VerifyIntegrity_Call) Return(err error) *MockAuditLogUseCase_VerifyIntegrity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogUseCase_VerifyIntegrity_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuditLogUseCase_VerifyIntegrity_Call {
	_c.Call.Return(run)
	return _c
}
