// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/auth/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Create(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Create(ctx interface{}, client interface{}) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, client)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(err error) *MockClientRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientRepository_Expecter) Get(ctx interface{}, clientID interface{}) *MockClientRepository_Get_Call {
	return &MockClientRepository_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientRepository_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Get_Call) Return(client *domain.Client, err error) *MockClientRepository_Get_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientRepository_Get_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) (*domain.Client, error)) *MockClientRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) List(ctx context.Context, offset int, limit int) ([]*domain.Client, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Client, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Client); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockClientRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockClientRepository_List_Call {
	return &MockClientRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockClientRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockClientRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientRepository_List_Call) Return(clients []*domain.Client, err error) *MockClientRepository_List_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockClientRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*domain.Client, error)) *MockClientRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Update(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Update(ctx interface{}, client interface{}) *MockClientRepository_Update_Call {
	return &MockClientRepository_Update_Call{Call: _e.mock.On("Update", ctx, client)}
}

func (_c *MockClientRepository_Update_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Update_Call) Return(err error) *MockClientRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_Update_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *MockClientRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Create(ctx context.Context, token *domain.Token) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Token
		if args[1] != nil {
			arg1 = args[1].(*domain.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(err error) *MockTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *domain.Token) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Get(ctx context.Context, tokenID uuid.UUID) (*domain.Token, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Token, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Token); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockTokenRepository_Expecter) Get(ctx interface{}, tokenID interface{}) *MockTokenRepository_Get_Call {
	return &MockTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, tokenID)}
}

func (_c *MockTokenRepository_Get_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Get_Call) Return(token *domain.Token, err error) *MockTokenRepository_Get_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_Get_Call) RunAndReturn(run func(ctx context.Context, tokenID uuid.UUID) (*domain.Token, error)) *MockTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*domain.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetByTokenHash_Call {
	return &MockTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Return(token *domain.Token, err error) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*domain.Token, error)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Update(ctx context.Context, token *domain.Token) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Update(ctx interface{}, token interface{}) *MockTokenRepository_Update_Call {
	return &MockTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, token)}
}

func (_c *MockTokenRepository_Update_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Token
		if args[1] != nil {
			arg1 = args[1].(*domain.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Update_Call) Return(err error) *MockTokenRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Update_Call) RunAndReturn(run func(ctx context.Context, token *domain.Token) error) *MockTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) Create(ctx context.Context, auditLog *domain.AuditLog) error {
	ret := _mock.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = returnFunc(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auditLog *domain.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx interface{}, auditLog interface{}) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, auditLog)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, auditLog *domain.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(err error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, auditLog *domain.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) List(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time) ([]*domain.AuditLog, error) {
	ret := _mock.Called(ctx, offset, limit, createdAtFrom, createdAtTo)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time) ([]*domain.AuditLog, error)); ok {
		return returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time) []*domain.AuditLog); ok {
		r0 = returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - createdAtFrom *time.Time
//   - createdAtTo *time.Time
func (_e *MockAuditLogRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}, createdAtFrom interface{}, createdAtTo interface{}) *MockAuditLogRepository_List_Call {
	return &MockAuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit, createdAtFrom, createdAtTo)}
}

func (_c *MockAuditLogRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time)) *MockAuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_List_Call) Return(auditLogs []*domain.AuditLog, err error) *MockAuditLogRepository_List_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockAuditLogRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time) ([]*domain.AuditLog, error)) *MockAuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientUseCase creates a new instance of MockClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientUseCase {
	mock := &MockClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientUseCase is an autogenerated mock type for the ClientUseCase type
type MockClientUseCase struct {
	mock.Mock
}

type MockClientUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientUseCase) EXPECT() *MockClientUseCase_Expecter {
	return &MockClientUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Create(ctx context.Context, createClientInput *domain.CreateClientInput) (*domain.CreateClientOutput, error) {
	ret := _mock.Called(ctx, createClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.CreateClientOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) (*domain.CreateClientOutput, error)); ok {
		return returnFunc(ctx, createClientInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateClientInput) *domain.CreateClientOutput); ok {
		r0 = returnFunc(ctx, createClientInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateClientOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateClientInput) error); ok {
		r1 = returnFunc(ctx, createClientInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createClientInput *domain.CreateClientInput
func (_e *MockClientUseCase_Expecter) Create(ctx interface{}, createClientInput interface{}) *MockClientUseCase_Create_Call {
	return &MockClientUseCase_Create_Call{Call: _e.mock.On("Create", ctx, createClientInput)}
}

func (_c *MockClientUseCase_Create_Call) Run(run func(ctx context.Context, createClientInput *domain.CreateClientInput)) *MockClientUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateClientInput
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateClientInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Create_Call) Return(createClientOutput *domain.CreateClientOutput, err error) *MockClientUseCase_Create_Call {
	_c.Call.Return(createClientOutput, err)
	return _c
}

func (_c *MockClientUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, createClientInput *domain.CreateClientInput) (*domain.CreateClientOutput, error)) *MockClientUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Delete(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClientUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Delete(ctx interface{}, clientID interface{}) *MockClientUseCase_Delete_Call {
	return &MockClientUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, clientID)}
}

func (_c *MockClientUseCase_Delete_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Delete_Call) Return(err error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockClientUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientUseCase_Expecter) Get(ctx interface{}, clientID interface{}) *MockClientUseCase_Get_Call {
	return &MockClientUseCase_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientUseCase_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Get_Call) Return(client *domain.Client, err error) *MockClientUseCase_Get_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) (*domain.Client, error)) *MockClientUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) List(ctx context.Context, offset int, limit int) ([]*domain.Client, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Client, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Client); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClientUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockClientUseCase_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockClientUseCase_List_Call {
	return &MockClientUseCase_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockClientUseCase_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockClientUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientUseCase_List_Call) Return(clients []*domain.Client, err error) *MockClientUseCase_List_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockClientUseCase_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*domain.Client, error)) *MockClientUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Update(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput) error {
	ret := _mock.Called(ctx, clientID, updateClientInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateClientInput) error); ok {
		r0 = returnFunc(ctx, clientID, updateClientInput)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - updateClientInput *domain.UpdateClientInput
func (_e *MockClientUseCase_Expecter) Update(ctx interface{}, clientID interface{}, updateClientInput interface{}) *MockClientUseCase_Update_Call {
	return &MockClientUseCase_Update_Call{Call: _e.mock.On("Update", ctx, clientID, updateClientInput)}
}

func (_c *MockClientUseCase_Update_Call) Run(run func(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput)) *MockClientUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.UpdateClientInput
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateClientInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Update_Call) Return(err error) *MockClientUseCase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, updateClientInput *domain.UpdateClientInput) error) *MockClientUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenUseCase creates a new instance of MockTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUseCase {
	mock := &MockTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenUseCase is an autogenerated mock type for the TokenUseCase type
type MockTokenUseCase struct {
	mock.Mock
}

type MockTokenUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenUseCase) EXPECT() *MockTokenUseCase_Expecter {
	return &MockTokenUseCase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) Authenticate(ctx context.Context, tokenHash string) (*domain.Client, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Client, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Client); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUseCase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockTokenUseCase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenUseCase_Expecter) Authenticate(ctx interface{}, tokenHash interface{}) *MockTokenUseCase_Authenticate_Call {
	return &MockTokenUseCase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, tokenHash)}
}

func (_c *MockTokenUseCase_Authenticate_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) Return(client *domain.Client, err error) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*domain.Client, error)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type MockTokenUseCase
func (_mock *MockTokenUseCase) Issue(ctx context.Context, issueTokenInput *domain.IssueTokenInput) (*domain.IssueTokenOutput, error) {
	ret := _mock.Called(ctx, issueTokenInput)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *domain.IssueTokenOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)); ok {
		return returnFunc(ctx, issueTokenInput)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) *domain.IssueTokenOutput); ok {
		r0 = returnFunc(ctx, issueTokenInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IssueTokenOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.IssueTokenInput) error); ok {
		r1 = returnFunc(ctx, issueTokenInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenUseCase_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenUseCase_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - issueTokenInput *domain.IssueTokenInput
func (_e *MockTokenUseCase_Expecter) Issue(ctx interface{}, issueTokenInput interface{}) *MockTokenUseCase_Issue_Call {
	return &MockTokenUseCase_Issue_Call{Call: _e.mock.On("Issue", ctx, issueTokenInput)}
}

func (_c *MockTokenUseCase_Issue_Call) Run(run func(ctx context.Context, issueTokenInput *domain.IssueTokenInput)) *MockTokenUseCase_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.IssueTokenInput
		if args[1] != nil {
			arg1 = args[1].(*domain.IssueTokenInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) Return(issueTokenOutput *domain.IssueTokenOutput, err error) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(issueTokenOutput, err)
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) RunAndReturn(run func(ctx context.Context, issueTokenInput *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogUseCase creates a new instance of MockAuditLogUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogUseCase {
	mock := &MockAuditLogUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogUseCase is an autogenerated mock type for the AuditLogUseCase type
type MockAuditLogUseCase struct {
	mock.Mock
}

type MockAuditLogUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogUseCase) EXPECT() *MockAuditLogUseCase_Expecter {
	return &MockAuditLogUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) Create(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any) error {
	ret := _mock.Called(ctx, requestID, clientID, capability, path, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.Capability, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, requestID, clientID, capability, path, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - clientID uuid.UUID
//   - capability domain.Capability
//   - path string
//   - metadata map[string]any
func (_e *MockAuditLogUseCase_Expecter) Create(ctx interface{}, requestID interface{}, clientID interface{}, capability interface{}, path interface{}, metadata interface{}) *MockAuditLogUseCase_Create_Call {
	return &MockAuditLogUseCase_Create_Call{Call: _e.mock.On("Create", ctx, requestID, clientID, capability, path, metadata)}
}

func (_c *MockAuditLogUseCase_Create_Call) Run(run func(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any)) *MockAuditLogUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 domain.Capability
		if args[3] != nil {
			arg3 = args[3].(domain.Capability)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 map[string]any
		if args[5] != nil {
			arg5 = args[5].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) Return(err error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID, clientID uuid.UUID, capability domain.Capability, path string, metadata map[string]any) error) *MockAuditLogUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAuditLogUseCase
func (_mock *MockAuditLogUseCase) List(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time) ([]*domain.AuditLog, error) {
	ret := _mock.Called(ctx, offset, limit, createdAtFrom, createdAtTo)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time) ([]*domain.AuditLog, error)); ok {
		return returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *time.Time, *time.Time) []*domain.AuditLog); ok {
		r0 = returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(ctx, offset, limit, createdAtFrom, createdAtTo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditLogUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - createdAtFrom *time.Time
//   - createdAtTo *time.Time
func (_e *MockAuditLogUseCase_Expecter) List(ctx interface{}, offset interface{}, limit interface{}, createdAtFrom interface{}, createdAtTo interface{}) *MockAuditLogUseCase_List_Call {
	return &MockAuditLogUseCase_List_Call{Call: _e.mock.On("List", ctx, offset, limit, createdAtFrom, createdAtTo)}
}

func (_c *MockAuditLogUseCase_List_Call) Run(run func(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time)) *MockAuditLogUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuditLogUseCase_List_Call) Return(auditLogs []*domain.AuditLog, err error) *MockAuditLogUseCase_List_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockAuditLogUseCase_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int, createdAtFrom *time.Time, createdAtTo *time.Time) ([]*domain.AuditLog, error)) *MockAuditLogUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}
