// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenUseCase is an autogenerated mock type for the TokenUseCase type
type MockTokenUseCase struct {
	mock.Mock
}

type MockTokenUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenUseCase) EXPECT() *MockTokenUseCase_Expecter {
	return &MockTokenUseCase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenUseCase) Authenticate(ctx context.Context, tokenHash string) (*domain.Client, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Client, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Client); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenUseCase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockTokenUseCase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenUseCase_Expecter) Authenticate(ctx interface{}, tokenHash interface{}) *MockTokenUseCase_Authenticate_Call {
	return &MockTokenUseCase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, tokenHash)}
}

func (_c *MockTokenUseCase_Authenticate_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) Return(_a0 *domain.Client, _a1 error) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenUseCase_Authenticate_Call) RunAndReturn(run func(context.Context, string) (*domain.Client, error)) *MockTokenUseCase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function with given fields: ctx, issueTokenInput
func (_m *MockTokenUseCase) Issue(ctx context.Context, issueTokenInput *domain.IssueTokenInput) (*domain.IssueTokenOutput, error) {
	ret := _m.Called(ctx, issueTokenInput)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *domain.IssueTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)); ok {
		return rf(ctx, issueTokenInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.IssueTokenInput) *domain.IssueTokenOutput); ok {
		r0 = rf(ctx, issueTokenInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.IssueTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.IssueTokenInput) error); ok {
		r1 = rf(ctx, issueTokenInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenUseCase_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenUseCase_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - issueTokenInput *domain.IssueTokenInput
func (_e *MockTokenUseCase_Expecter) Issue(ctx interface{}, issueTokenInput interface{}) *MockTokenUseCase_Issue_Call {
	return &MockTokenUseCase_Issue_Call{Call: _e.mock.On("Issue", ctx, issueTokenInput)}
}

func (_c *MockTokenUseCase_Issue_Call) Run(run func(ctx context.Context, issueTokenInput *domain.IssueTokenInput)) *MockTokenUseCase_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.IssueTokenInput))
	})
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) Return(_a0 *domain.IssueTokenOutput, _a1 error) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenUseCase_Issue_Call) RunAndReturn(run func(context.Context, *domain.IssueTokenInput) (*domain.IssueTokenOutput, error)) *MockTokenUseCase_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenUseCase creates a new instance of MockTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenUseCase {
	mock := &MockTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
