// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) Create(ctx context.Context, token *domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Token))
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(_a0 error) *MockTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Token) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, tokenID
func (_m *MockTokenRepository) Get(ctx context.Context, tokenID uuid.UUID) (*domain.Token, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Token, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Token); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockTokenRepository_Expecter) Get(ctx interface{}, tokenID interface{}) *MockTokenRepository_Get_Call {
	return &MockTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, tokenID)}
}

func (_c *MockTokenRepository_Get_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenRepository_Get_Call) Return(_a0 *domain.Token, _a1 error) *MockTokenRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Token, error)) *MockTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*domain.Token, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetByTokenHash_Call {
	return &MockTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Return(_a0 *domain.Token, _a1 error) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.Token, error)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) Update(ctx context.Context, token *domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Update(ctx interface{}, token interface{}) *MockTokenRepository_Update_Call {
	return &MockTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, token)}
}

func (_c *MockTokenRepository_Update_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Token))
	})
	return _c
}

func (_c *MockTokenRepository_Update_Call) Return(_a0 error) *MockTokenRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Token) error) *MockTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
