// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/auth/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientRepository creates a new instance of MockClientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRepository {
	mock := &MockClientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientRepository is an autogenerated mock type for the ClientRepository type
type MockClientRepository struct {
	mock.Mock
}

type MockClientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRepository) EXPECT() *MockClientRepository_Expecter {
	return &MockClientRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Create(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClientRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Create(ctx any, client any) *MockClientRepository_Create_Call {
	return &MockClientRepository_Create_Call{Call: _e.mock.On("Create", ctx, client)}
}

func (_c *MockClientRepository_Create_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Create_Call) Return(err error) *MockClientRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_Create_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *MockClientRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Get(ctx context.Context, clientID uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClientRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockClientRepository_Expecter) Get(ctx any, clientID any) *MockClientRepository_Get_Call {
	return &MockClientRepository_Get_Call{Call: _e.mock.On("Get", ctx, clientID)}
}

func (_c *MockClientRepository_Get_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockClientRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Get_Call) Return(client *domain.Client, err error) *MockClientRepository_Get_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockClientRepository_Get_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) (*domain.Client, error)) *MockClientRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) ListCursor(ctx context.Context, afterID *uuid.UUID, limit int) ([]*domain.Client, error) {
	ret := _mock.Called(ctx, afterID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int) ([]*domain.Client, error)); ok {
		return returnFunc(ctx, afterID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int) []*domain.Client); ok {
		r0 = returnFunc(ctx, afterID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, afterID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientRepository_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockClientRepository_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID *uuid.UUID
//   - limit int
func (_e *MockClientRepository_Expecter) ListCursor(ctx any, afterID any, limit any) *MockClientRepository_ListCursor_Call {
	return &MockClientRepository_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterID, limit)}
}

func (_c *MockClientRepository_ListCursor_Call) Run(run func(ctx context.Context, afterID *uuid.UUID, limit int)) *MockClientRepository_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientRepository_ListCursor_Call) Return(clients []*domain.Client, err error) *MockClientRepository_ListCursor_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockClientRepository_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterID *uuid.UUID, limit int) ([]*domain.Client, error)) *MockClientRepository_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) Update(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClientRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *MockClientRepository_Expecter) Update(ctx any, client any) *MockClientRepository_Update_Call {
	return &MockClientRepository_Update_Call{Call: _e.mock.On("Update", ctx, client)}
}

func (_c *MockClientRepository_Update_Call) Run(run func(ctx context.Context, client *domain.Client)) *MockClientRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientRepository_Update_Call) Return(err error) *MockClientRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_Update_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *MockClientRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLockState provides a mock function for the type MockClientRepository
func (_mock *MockClientRepository) UpdateLockState(ctx context.Context, clientID uuid.UUID, failedAttempts int, lockedUntil *time.Time) error {
	ret := _mock.Called(ctx, clientID, failedAttempts, lockedUntil)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLockState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, *time.Time) error); ok {
		r0 = returnFunc(ctx, clientID, failedAttempts, lockedUntil)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientRepository_UpdateLockState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLockState'
type MockClientRepository_UpdateLockState_Call struct {
	*mock.Call
}

// UpdateLockState is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
//   - failedAttempts int
//   - lockedUntil *time.Time
func (_e *MockClientRepository_Expecter) UpdateLockState(ctx any, clientID any, failedAttempts any, lockedUntil any) *MockClientRepository_UpdateLockState_Call {
	return &MockClientRepository_UpdateLockState_Call{Call: _e.mock.On("UpdateLockState", ctx, clientID, failedAttempts, lockedUntil)}
}

func (_c *MockClientRepository_UpdateLockState_Call) Run(run func(ctx context.Context, clientID uuid.UUID, failedAttempts int, lockedUntil *time.Time)) *MockClientRepository_UpdateLockState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientRepository_UpdateLockState_Call) Return(err error) *MockClientRepository_UpdateLockState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientRepository_UpdateLockState_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID, failedAttempts int, lockedUntil *time.Time) error) *MockClientRepository_UpdateLockState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Create(ctx context.Context, token *domain.Token) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Create(ctx any, token any) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Token
		if args[1] != nil {
			arg1 = args[1].(*domain.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(err error) *MockTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *domain.Token) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Get(ctx context.Context, tokenID uuid.UUID) (*domain.Token, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Token, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Token); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTokenRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockTokenRepository_Expecter) Get(ctx any, tokenID any) *MockTokenRepository_Get_Call {
	return &MockTokenRepository_Get_Call{Call: _e.mock.On("Get", ctx, tokenID)}
}

func (_c *MockTokenRepository_Get_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockTokenRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Get_Call) Return(token *domain.Token, err error) *MockTokenRepository_Get_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_Get_Call) RunAndReturn(run func(ctx context.Context, tokenID uuid.UUID) (*domain.Token, error)) *MockTokenRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*domain.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockTokenRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByTokenHash(ctx any, tokenHash any) *MockTokenRepository_GetByTokenHash_Call {
	return &MockTokenRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) Return(token *domain.Token, err error) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*domain.Token, error)) *MockTokenRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeExpiredAndRevoked provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) PurgeExpiredAndRevoked(ctx context.Context, olderThan time.Time) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PurgeExpiredAndRevoked")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_PurgeExpiredAndRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeExpiredAndRevoked'
type MockTokenRepository_PurgeExpiredAndRevoked_Call struct {
	*mock.Call
}

// PurgeExpiredAndRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
func (_e *MockTokenRepository_Expecter) PurgeExpiredAndRevoked(ctx any, olderThan any) *MockTokenRepository_PurgeExpiredAndRevoked_Call {
	return &MockTokenRepository_PurgeExpiredAndRevoked_Call{Call: _e.mock.On("PurgeExpiredAndRevoked", ctx, olderThan)}
}

func (_c *MockTokenRepository_PurgeExpiredAndRevoked_Call) Run(run func(ctx context.Context, olderThan time.Time)) *MockTokenRepository_PurgeExpiredAndRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_PurgeExpiredAndRevoked_Call) Return(n int64, err error) *MockTokenRepository_PurgeExpiredAndRevoked_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTokenRepository_PurgeExpiredAndRevoked_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time) (int64, error)) *MockTokenRepository_PurgeExpiredAndRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByClientID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) RevokeByClientID(ctx context.Context, clientID uuid.UUID) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByClientID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_RevokeByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByClientID'
type MockTokenRepository_RevokeByClientID_Call struct {
	*mock.Call
}

// RevokeByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID uuid.UUID
func (_e *MockTokenRepository_Expecter) RevokeByClientID(ctx any, clientID any) *MockTokenRepository_RevokeByClientID_Call {
	return &MockTokenRepository_RevokeByClientID_Call{Call: _e.mock.On("RevokeByClientID", ctx, clientID)}
}

func (_c *MockTokenRepository_RevokeByClientID_Call) Run(run func(ctx context.Context, clientID uuid.UUID)) *MockTokenRepository_RevokeByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_RevokeByClientID_Call) Return(err error) *MockTokenRepository_RevokeByClientID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_RevokeByClientID_Call) RunAndReturn(run func(ctx context.Context, clientID uuid.UUID) error) *MockTokenRepository_RevokeByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByTokenID provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) RevokeByTokenID(ctx context.Context, tokenID uuid.UUID) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByTokenID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_RevokeByTokenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByTokenID'
type MockTokenRepository_RevokeByTokenID_Call struct {
	*mock.Call
}

// RevokeByTokenID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID uuid.UUID
func (_e *MockTokenRepository_Expecter) RevokeByTokenID(ctx any, tokenID any) *MockTokenRepository_RevokeByTokenID_Call {
	return &MockTokenRepository_RevokeByTokenID_Call{Call: _e.mock.On("RevokeByTokenID", ctx, tokenID)}
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) Run(run func(ctx context.Context, tokenID uuid.UUID)) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) Return(err error) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_RevokeByTokenID_Call) RunAndReturn(run func(ctx context.Context, tokenID uuid.UUID) error) *MockTokenRepository_RevokeByTokenID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) Update(ctx context.Context, token *domain.Token) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Update(ctx any, token any) *MockTokenRepository_Update_Call {
	return &MockTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, token)}
}

func (_c *MockTokenRepository_Update_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Token
		if args[1] != nil {
			arg1 = args[1].(*domain.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_Update_Call) Return(err error) *MockTokenRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_Update_Call) RunAndReturn(run func(ctx context.Context, token *domain.Token) error) *MockTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) Create(ctx context.Context, auditLog *domain.AuditLog) error {
	ret := _mock.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = returnFunc(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - auditLog *domain.AuditLog
func (_e *MockAuditLogRepository_Expecter) Create(ctx any, auditLog any) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, auditLog)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, auditLog *domain.AuditLog)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(err error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, auditLog *domain.AuditLog) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) DeleteOlderThan(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, olderThan, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) (int64, error)); ok {
		return returnFunc(ctx, olderThan, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) int64); ok {
		r0 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, bool) error); ok {
		r1 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockAuditLogRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
//   - dryRun bool
func (_e *MockAuditLogRepository_Expecter) DeleteOlderThan(ctx any, olderThan any, dryRun any) *MockAuditLogRepository_DeleteOlderThan_Call {
	return &MockAuditLogRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, olderThan, dryRun)}
}

func (_c *MockAuditLogRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, olderThan time.Time, dryRun bool)) *MockAuditLogRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_DeleteOlderThan_Call) Return(n int64, err error) *MockAuditLogRepository_DeleteOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuditLogRepository_DeleteOlderThan_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error)) *MockAuditLogRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) Get(ctx context.Context, id uuid.UUID) (*domain.AuditLog, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.AuditLog, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.AuditLog); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAuditLogRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuditLogRepository_Expecter) Get(ctx any, id any) *MockAuditLogRepository_Get_Call {
	return &MockAuditLogRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAuditLogRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuditLogRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_Get_Call) Return(auditLog *domain.AuditLog, err error) *MockAuditLogRepository_Get_Call {
	_c.Call.Return(auditLog, err)
	return _c
}

func (_c *MockAuditLogRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.AuditLog, error)) *MockAuditLogRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) ListCursor(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID) ([]*domain.AuditLog, error) {
	ret := _mock.Called(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.AuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) ([]*domain.AuditLog, error)); ok {
		return returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) []*domain.AuditLog); ok {
		r0 = returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID, int, *time.Time, *time.Time, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditLogRepository_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockAuditLogRepository_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterID *uuid.UUID
//   - limit int
//   - createdAtFrom *time.Time
//   - createdAtTo *time.Time
//   - clientID *uuid.UUID
func (_e *MockAuditLogRepository_Expecter) ListCursor(ctx any, afterID any, limit any, createdAtFrom any, createdAtTo any, clientID any) *MockAuditLogRepository_ListCursor_Call {
	return &MockAuditLogRepository_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterID, limit, createdAtFrom, createdAtTo, clientID)}
}

func (_c *MockAuditLogRepository_ListCursor_Call) Run(run func(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID)) *MockAuditLogRepository_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 *uuid.UUID
		if args[5] != nil {
			arg5 = args[5].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_ListCursor_Call) Return(auditLogs []*domain.AuditLog, err error) *MockAuditLogRepository_ListCursor_Call {
	_c.Call.Return(auditLogs, err)
	return _c
}

func (_c *MockAuditLogRepository_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterID *uuid.UUID, limit int, createdAtFrom *time.Time, createdAtTo *time.Time, clientID *uuid.UUID) ([]*domain.AuditLog, error)) *MockAuditLogRepository_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}
