// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAEAD is an autogenerated mock type for the AEAD type
type MockAEAD struct {
	mock.Mock
}

type MockAEAD_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAEAD) EXPECT() *MockAEAD_Expecter {
	return &MockAEAD_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: ciphertext, nonce, aad
func (_m *MockAEAD) Decrypt(ciphertext []byte, nonce []byte, aad []byte) ([]byte, error) {
	ret := _m.Called(ciphertext, nonce, aad)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return rf(ciphertext, nonce, aad)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = rf(ciphertext, nonce, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = rf(ciphertext, nonce, aad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAEAD_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockAEAD_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext []byte
//   - nonce []byte
//   - aad []byte
func (_e *MockAEAD_Expecter) Decrypt(ciphertext interface{}, nonce interface{}, aad interface{}) *MockAEAD_Decrypt_Call {
	return &MockAEAD_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext, nonce, aad)}
}

func (_c *MockAEAD_Decrypt_Call) Run(run func(ciphertext []byte, nonce []byte, aad []byte)) *MockAEAD_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *MockAEAD_Decrypt_Call) Return(_a0 []byte, _a1 error) *MockAEAD_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAEAD_Decrypt_Call) RunAndReturn(run func([]byte, []byte, []byte) ([]byte, error)) *MockAEAD_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: plaintext, aad
func (_m *MockAEAD) Encrypt(plaintext []byte, aad []byte) ([]byte, []byte, error) {
	ret := _m.Called(plaintext, aad)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) ([]byte, []byte, error)); ok {
		return rf(plaintext, aad)
	}
	if rf, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = rf(plaintext, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []byte) []byte); ok {
		r1 = rf(plaintext, aad)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte, []byte) error); ok {
		r2 = rf(plaintext, aad)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAEAD_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockAEAD_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext []byte
//   - aad []byte
func (_e *MockAEAD_Expecter) Encrypt(plaintext interface{}, aad interface{}) *MockAEAD_Encrypt_Call {
	return &MockAEAD_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext, aad)}
}

func (_c *MockAEAD_Encrypt_Call) Run(run func(plaintext []byte, aad []byte)) *MockAEAD_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockAEAD_Encrypt_Call) Return(ciphertext []byte, nonce []byte, err error) *MockAEAD_Encrypt_Call {
	_c.Call.Return(ciphertext, nonce, err)
	return _c
}

func (_c *MockAEAD_Encrypt_Call) RunAndReturn(run func([]byte, []byte) ([]byte, []byte, error)) *MockAEAD_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAEAD creates a new instance of MockAEAD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAEAD(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAEAD {
	mock := &MockAEAD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
