// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/allisson/secrets/internal/crypto/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

type MockKeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyManager) EXPECT() *MockKeyManager_Expecter {
	return &MockKeyManager_Expecter{mock: &_m.Mock}
}

// CreateDek provides a mock function with given fields: kek, alg
func (_m *MockKeyManager) CreateDek(kek *domain.Kek, alg domain.Algorithm) (domain.Dek, error) {
	ret := _m.Called(kek, alg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDek")
	}

	var r0 domain.Dek
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Kek, domain.Algorithm) (domain.Dek, error)); ok {
		return rf(kek, alg)
	}
	if rf, ok := ret.Get(0).(func(*domain.Kek, domain.Algorithm) domain.Dek); ok {
		r0 = rf(kek, alg)
	} else {
		r0 = ret.Get(0).(domain.Dek)
	}

	if rf, ok := ret.Get(1).(func(*domain.Kek, domain.Algorithm) error); ok {
		r1 = rf(kek, alg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_CreateDek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDek'
type MockKeyManager_CreateDek_Call struct {
	*mock.Call
}

// CreateDek is a helper method to define mock.On call
//   - kek *domain.Kek
//   - alg domain.Algorithm
func (_e *MockKeyManager_Expecter) CreateDek(kek interface{}, alg interface{}) *MockKeyManager_CreateDek_Call {
	return &MockKeyManager_CreateDek_Call{Call: _e.mock.On("CreateDek", kek, alg)}
}

func (_c *MockKeyManager_CreateDek_Call) Run(run func(kek *domain.Kek, alg domain.Algorithm)) *MockKeyManager_CreateDek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Kek), args[1].(domain.Algorithm))
	})
	return _c
}

func (_c *MockKeyManager_CreateDek_Call) Return(_a0 domain.Dek, _a1 error) *MockKeyManager_CreateDek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_CreateDek_Call) RunAndReturn(run func(*domain.Kek, domain.Algorithm) (domain.Dek, error)) *MockKeyManager_CreateDek_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKek provides a mock function with given fields: masterKey, alg
func (_m *MockKeyManager) CreateKek(masterKey *domain.MasterKey, alg domain.Algorithm) (domain.Kek, error) {
	ret := _m.Called(masterKey, alg)

	if len(ret) == 0 {
		panic("no return value specified for CreateKek")
	}

	var r0 domain.Kek
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.MasterKey, domain.Algorithm) (domain.Kek, error)); ok {
		return rf(masterKey, alg)
	}
	if rf, ok := ret.Get(0).(func(*domain.MasterKey, domain.Algorithm) domain.Kek); ok {
		r0 = rf(masterKey, alg)
	} else {
		r0 = ret.Get(0).(domain.Kek)
	}

	if rf, ok := ret.Get(1).(func(*domain.MasterKey, domain.Algorithm) error); ok {
		r1 = rf(masterKey, alg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_CreateKek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKek'
type MockKeyManager_CreateKek_Call struct {
	*mock.Call
}

// CreateKek is a helper method to define mock.On call
//   - masterKey *domain.MasterKey
//   - alg domain.Algorithm
func (_e *MockKeyManager_Expecter) CreateKek(masterKey interface{}, alg interface{}) *MockKeyManager_CreateKek_Call {
	return &MockKeyManager_CreateKek_Call{Call: _e.mock.On("CreateKek", masterKey, alg)}
}

func (_c *MockKeyManager_CreateKek_Call) Run(run func(masterKey *domain.MasterKey, alg domain.Algorithm)) *MockKeyManager_CreateKek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.MasterKey), args[1].(domain.Algorithm))
	})
	return _c
}

func (_c *MockKeyManager_CreateKek_Call) Return(_a0 domain.Kek, _a1 error) *MockKeyManager_CreateKek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_CreateKek_Call) RunAndReturn(run func(*domain.MasterKey, domain.Algorithm) (domain.Kek, error)) *MockKeyManager_CreateKek_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptDek provides a mock function with given fields: dek, kek
func (_m *MockKeyManager) DecryptDek(dek *domain.Dek, kek *domain.Kek) ([]byte, error) {
	ret := _m.Called(dek, kek)

	if len(ret) == 0 {
		panic("no return value specified for DecryptDek")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Dek, *domain.Kek) ([]byte, error)); ok {
		return rf(dek, kek)
	}
	if rf, ok := ret.Get(0).(func(*domain.Dek, *domain.Kek) []byte); ok {
		r0 = rf(dek, kek)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Dek, *domain.Kek) error); ok {
		r1 = rf(dek, kek)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_DecryptDek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptDek'
type MockKeyManager_DecryptDek_Call struct {
	*mock.Call
}

// DecryptDek is a helper method to define mock.On call
//   - dek *domain.Dek
//   - kek *domain.Kek
func (_e *MockKeyManager_Expecter) DecryptDek(dek interface{}, kek interface{}) *MockKeyManager_DecryptDek_Call {
	return &MockKeyManager_DecryptDek_Call{Call: _e.mock.On("DecryptDek", dek, kek)}
}

func (_c *MockKeyManager_DecryptDek_Call) Run(run func(dek *domain.Dek, kek *domain.Kek)) *MockKeyManager_DecryptDek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Dek), args[1].(*domain.Kek))
	})
	return _c
}

func (_c *MockKeyManager_DecryptDek_Call) Return(_a0 []byte, _a1 error) *MockKeyManager_DecryptDek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_DecryptDek_Call) RunAndReturn(run func(*domain.Dek, *domain.Kek) ([]byte, error)) *MockKeyManager_DecryptDek_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptKek provides a mock function with given fields: kek, masterKey
func (_m *MockKeyManager) DecryptKek(kek *domain.Kek, masterKey *domain.MasterKey) ([]byte, error) {
	ret := _m.Called(kek, masterKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptKek")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Kek, *domain.MasterKey) ([]byte, error)); ok {
		return rf(kek, masterKey)
	}
	if rf, ok := ret.Get(0).(func(*domain.Kek, *domain.MasterKey) []byte); ok {
		r0 = rf(kek, masterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Kek, *domain.MasterKey) error); ok {
		r1 = rf(kek, masterKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKeyManager_DecryptKek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptKek'
type MockKeyManager_DecryptKek_Call struct {
	*mock.Call
}

// DecryptKek is a helper method to define mock.On call
//   - kek *domain.Kek
//   - masterKey *domain.MasterKey
func (_e *MockKeyManager_Expecter) DecryptKek(kek interface{}, masterKey interface{}) *MockKeyManager_DecryptKek_Call {
	return &MockKeyManager_DecryptKek_Call{Call: _e.mock.On("DecryptKek", kek, masterKey)}
}

func (_c *MockKeyManager_DecryptKek_Call) Run(run func(kek *domain.Kek, masterKey *domain.MasterKey)) *MockKeyManager_DecryptKek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Kek), args[1].(*domain.MasterKey))
	})
	return _c
}

func (_c *MockKeyManager_DecryptKek_Call) Return(_a0 []byte, _a1 error) *MockKeyManager_DecryptKek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKeyManager_DecryptKek_Call) RunAndReturn(run func(*domain.Kek, *domain.MasterKey) ([]byte, error)) *MockKeyManager_DecryptKek_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyManager creates a new instance of MockKeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyManager {
	mock := &MockKeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
