// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/allisson/secrets/internal/crypto/domain"
	"github.com/allisson/secrets/internal/crypto/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAEAD creates a new instance of MockAEAD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAEAD(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAEAD {
	mock := &MockAEAD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAEAD is an autogenerated mock type for the AEAD type
type MockAEAD struct {
	mock.Mock
}

type MockAEAD_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAEAD) EXPECT() *MockAEAD_Expecter {
	return &MockAEAD_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockAEAD
func (_mock *MockAEAD) Decrypt(ciphertext []byte, nonce []byte, aad []byte) ([]byte, error) {
	ret := _mock.Called(ciphertext, nonce, aad)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, []byte) ([]byte, error)); ok {
		return returnFunc(ciphertext, nonce, aad)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte, []byte) []byte); ok {
		r0 = returnFunc(ciphertext, nonce, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte, []byte) error); ok {
		r1 = returnFunc(ciphertext, nonce, aad)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAEAD_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockAEAD_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ciphertext []byte
//   - nonce []byte
//   - aad []byte
func (_e *MockAEAD_Expecter) Decrypt(ciphertext interface{}, nonce interface{}, aad interface{}) *MockAEAD_Decrypt_Call {
	return &MockAEAD_Decrypt_Call{Call: _e.mock.On("Decrypt", ciphertext, nonce, aad)}
}

func (_c *MockAEAD_Decrypt_Call) Run(run func(ciphertext []byte, nonce []byte, aad []byte)) *MockAEAD_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAEAD_Decrypt_Call) Return(bytes []byte, err error) *MockAEAD_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAEAD_Decrypt_Call) RunAndReturn(run func(ciphertext []byte, nonce []byte, aad []byte) ([]byte, error)) *MockAEAD_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockAEAD
func (_mock *MockAEAD) Encrypt(plaintext []byte, aad []byte) ([]byte, []byte, error) {
	ret := _mock.Called(plaintext, aad)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) ([]byte, []byte, error)); ok {
		return returnFunc(plaintext, aad)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = returnFunc(plaintext, aad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) []byte); ok {
		r1 = returnFunc(plaintext, aad)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]byte, []byte) error); ok {
		r2 = returnFunc(plaintext, aad)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAEAD_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockAEAD_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext []byte
//   - aad []byte
func (_e *MockAEAD_Expecter) Encrypt(plaintext interface{}, aad interface{}) *MockAEAD_Encrypt_Call {
	return &MockAEAD_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext, aad)}
}

func (_c *MockAEAD_Encrypt_Call) Run(run func(plaintext []byte, aad []byte)) *MockAEAD_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAEAD_Encrypt_Call) Return(ciphertext []byte, nonce []byte, err error) *MockAEAD_Encrypt_Call {
	_c.Call.Return(ciphertext, nonce, err)
	return _c
}

func (_c *MockAEAD_Encrypt_Call) RunAndReturn(run func(plaintext []byte, aad []byte) ([]byte, []byte, error)) *MockAEAD_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NonceSize provides a mock function for the type MockAEAD
func (_mock *MockAEAD) NonceSize() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NonceSize")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockAEAD_NonceSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NonceSize'
type MockAEAD_NonceSize_Call struct {
	*mock.Call
}

// NonceSize is a helper method to define mock.On call
func (_e *MockAEAD_Expecter) NonceSize() *MockAEAD_NonceSize_Call {
	return &MockAEAD_NonceSize_Call{Call: _e.mock.On("NonceSize")}
}

func (_c *MockAEAD_NonceSize_Call) Run(run func()) *MockAEAD_NonceSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAEAD_NonceSize_Call) Return(n int) *MockAEAD_NonceSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockAEAD_NonceSize_Call) RunAndReturn(run func() int) *MockAEAD_NonceSize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAEADManager creates a new instance of MockAEADManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAEADManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAEADManager {
	mock := &MockAEADManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAEADManager is an autogenerated mock type for the AEADManager type
type MockAEADManager struct {
	mock.Mock
}

type MockAEADManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAEADManager) EXPECT() *MockAEADManager_Expecter {
	return &MockAEADManager_Expecter{mock: &_m.Mock}
}

// CreateCipher provides a mock function for the type MockAEADManager
func (_mock *MockAEADManager) CreateCipher(key []byte, alg domain.Algorithm) (service.AEAD, error) {
	ret := _mock.Called(key, alg)

	if len(ret) == 0 {
		panic("no return value specified for CreateCipher")
	}

	var r0 service.AEAD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, domain.Algorithm) (service.AEAD, error)); ok {
		return returnFunc(key, alg)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, domain.Algorithm) service.AEAD); ok {
		r0 = returnFunc(key, alg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AEAD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, domain.Algorithm) error); ok {
		r1 = returnFunc(key, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAEADManager_CreateCipher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCipher'
type MockAEADManager_CreateCipher_Call struct {
	*mock.Call
}

// CreateCipher is a helper method to define mock.On call
//   - key []byte
//   - alg domain.Algorithm
func (_e *MockAEADManager_Expecter) CreateCipher(key interface{}, alg interface{}) *MockAEADManager_CreateCipher_Call {
	return &MockAEADManager_CreateCipher_Call{Call: _e.mock.On("CreateCipher", key, alg)}
}

func (_c *MockAEADManager_CreateCipher_Call) Run(run func(key []byte, alg domain.Algorithm)) *MockAEADManager_CreateCipher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 domain.Algorithm
		if args[1] != nil {
			arg1 = args[1].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAEADManager_CreateCipher_Call) Return(aEAD service.AEAD, err error) *MockAEADManager_CreateCipher_Call {
	_c.Call.Return(aEAD, err)
	return _c
}

func (_c *MockAEADManager_CreateCipher_Call) RunAndReturn(run func(key []byte, alg domain.Algorithm) (service.AEAD, error)) *MockAEADManager_CreateCipher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyManager creates a new instance of MockKeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyManager {
	mock := &MockKeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyManager is an autogenerated mock type for the KeyManager type
type MockKeyManager struct {
	mock.Mock
}

type MockKeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyManager) EXPECT() *MockKeyManager_Expecter {
	return &MockKeyManager_Expecter{mock: &_m.Mock}
}

// CreateDek provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) CreateDek(kek *domain.Kek, alg domain.Algorithm) (domain.Dek, error) {
	ret := _mock.Called(kek, alg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDek")
	}

	var r0 domain.Dek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Kek, domain.Algorithm) (domain.Dek, error)); ok {
		return returnFunc(kek, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.Kek, domain.Algorithm) domain.Dek); ok {
		r0 = returnFunc(kek, alg)
	} else {
		r0 = ret.Get(0).(domain.Dek)
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.Kek, domain.Algorithm) error); ok {
		r1 = returnFunc(kek, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManager_CreateDek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDek'
type MockKeyManager_CreateDek_Call struct {
	*mock.Call
}

// CreateDek is a helper method to define mock.On call
//   - kek *domain.Kek
//   - alg domain.Algorithm
func (_e *MockKeyManager_Expecter) CreateDek(kek interface{}, alg interface{}) *MockKeyManager_CreateDek_Call {
	return &MockKeyManager_CreateDek_Call{Call: _e.mock.On("CreateDek", kek, alg)}
}

func (_c *MockKeyManager_CreateDek_Call) Run(run func(kek *domain.Kek, alg domain.Algorithm)) *MockKeyManager_CreateDek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Kek
		if args[0] != nil {
			arg0 = args[0].(*domain.Kek)
		}
		var arg1 domain.Algorithm
		if args[1] != nil {
			arg1 = args[1].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_CreateDek_Call) Return(dek domain.Dek, err error) *MockKeyManager_CreateDek_Call {
	_c.Call.Return(dek, err)
	return _c
}

func (_c *MockKeyManager_CreateDek_Call) RunAndReturn(run func(kek *domain.Kek, alg domain.Algorithm) (domain.Dek, error)) *MockKeyManager_CreateDek_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKek provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) CreateKek(masterKey *domain.MasterKey, alg domain.Algorithm) (domain.Kek, error) {
	ret := _mock.Called(masterKey, alg)

	if len(ret) == 0 {
		panic("no return value specified for CreateKek")
	}

	var r0 domain.Kek
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.MasterKey, domain.Algorithm) (domain.Kek, error)); ok {
		return returnFunc(masterKey, alg)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.MasterKey, domain.Algorithm) domain.Kek); ok {
		r0 = returnFunc(masterKey, alg)
	} else {
		r0 = ret.Get(0).(domain.Kek)
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.MasterKey, domain.Algorithm) error); ok {
		r1 = returnFunc(masterKey, alg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManager_CreateKek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKek'
type MockKeyManager_CreateKek_Call struct {
	*mock.Call
}

// CreateKek is a helper method to define mock.On call
//   - masterKey *domain.MasterKey
//   - alg domain.Algorithm
func (_e *MockKeyManager_Expecter) CreateKek(masterKey interface{}, alg interface{}) *MockKeyManager_CreateKek_Call {
	return &MockKeyManager_CreateKek_Call{Call: _e.mock.On("CreateKek", masterKey, alg)}
}

func (_c *MockKeyManager_CreateKek_Call) Run(run func(masterKey *domain.MasterKey, alg domain.Algorithm)) *MockKeyManager_CreateKek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.MasterKey
		if args[0] != nil {
			arg0 = args[0].(*domain.MasterKey)
		}
		var arg1 domain.Algorithm
		if args[1] != nil {
			arg1 = args[1].(domain.Algorithm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_CreateKek_Call) Return(kek domain.Kek, err error) *MockKeyManager_CreateKek_Call {
	_c.Call.Return(kek, err)
	return _c
}

func (_c *MockKeyManager_CreateKek_Call) RunAndReturn(run func(masterKey *domain.MasterKey, alg domain.Algorithm) (domain.Kek, error)) *MockKeyManager_CreateKek_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptDek provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) DecryptDek(dek *domain.Dek, kek *domain.Kek) ([]byte, error) {
	ret := _mock.Called(dek, kek)

	if len(ret) == 0 {
		panic("no return value specified for DecryptDek")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Dek, *domain.Kek) ([]byte, error)); ok {
		return returnFunc(dek, kek)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.Dek, *domain.Kek) []byte); ok {
		r0 = returnFunc(dek, kek)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.Dek, *domain.Kek) error); ok {
		r1 = returnFunc(dek, kek)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManager_DecryptDek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptDek'
type MockKeyManager_DecryptDek_Call struct {
	*mock.Call
}

// DecryptDek is a helper method to define mock.On call
//   - dek *domain.Dek
//   - kek *domain.Kek
func (_e *MockKeyManager_Expecter) DecryptDek(dek interface{}, kek interface{}) *MockKeyManager_DecryptDek_Call {
	return &MockKeyManager_DecryptDek_Call{Call: _e.mock.On("DecryptDek", dek, kek)}
}

func (_c *MockKeyManager_DecryptDek_Call) Run(run func(dek *domain.Dek, kek *domain.Kek)) *MockKeyManager_DecryptDek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Dek
		if args[0] != nil {
			arg0 = args[0].(*domain.Dek)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_DecryptDek_Call) Return(bytes []byte, err error) *MockKeyManager_DecryptDek_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKeyManager_DecryptDek_Call) RunAndReturn(run func(dek *domain.Dek, kek *domain.Kek) ([]byte, error)) *MockKeyManager_DecryptDek_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptKek provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) DecryptKek(kek *domain.Kek, masterKey *domain.MasterKey) ([]byte, error) {
	ret := _mock.Called(kek, masterKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptKek")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Kek, *domain.MasterKey) ([]byte, error)); ok {
		return returnFunc(kek, masterKey)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.Kek, *domain.MasterKey) []byte); ok {
		r0 = returnFunc(kek, masterKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.Kek, *domain.MasterKey) error); ok {
		r1 = returnFunc(kek, masterKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManager_DecryptKek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptKek'
type MockKeyManager_DecryptKek_Call struct {
	*mock.Call
}

// DecryptKek is a helper method to define mock.On call
//   - kek *domain.Kek
//   - masterKey *domain.MasterKey
func (_e *MockKeyManager_Expecter) DecryptKek(kek interface{}, masterKey interface{}) *MockKeyManager_DecryptKek_Call {
	return &MockKeyManager_DecryptKek_Call{Call: _e.mock.On("DecryptKek", kek, masterKey)}
}

func (_c *MockKeyManager_DecryptKek_Call) Run(run func(kek *domain.Kek, masterKey *domain.MasterKey)) *MockKeyManager_DecryptKek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Kek
		if args[0] != nil {
			arg0 = args[0].(*domain.Kek)
		}
		var arg1 *domain.MasterKey
		if args[1] != nil {
			arg1 = args[1].(*domain.MasterKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_DecryptKek_Call) Return(bytes []byte, err error) *MockKeyManager_DecryptKek_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKeyManager_DecryptKek_Call) RunAndReturn(run func(kek *domain.Kek, masterKey *domain.MasterKey) ([]byte, error)) *MockKeyManager_DecryptKek_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptDek provides a mock function for the type MockKeyManager
func (_mock *MockKeyManager) EncryptDek(dekKey []byte, kek *domain.Kek) ([]byte, []byte, error) {
	ret := _mock.Called(dekKey, kek)

	if len(ret) == 0 {
		panic("no return value specified for EncryptDek")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte, *domain.Kek) ([]byte, []byte, error)); ok {
		return returnFunc(dekKey, kek)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, *domain.Kek) []byte); ok {
		r0 = returnFunc(dekKey, kek)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, *domain.Kek) []byte); ok {
		r1 = returnFunc(dekKey, kek)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func([]byte, *domain.Kek) error); ok {
		r2 = returnFunc(dekKey, kek)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeyManager_EncryptDek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptDek'
type MockKeyManager_EncryptDek_Call struct {
	*mock.Call
}

// EncryptDek is a helper method to define mock.On call
//   - dekKey []byte
//   - kek *domain.Kek
func (_e *MockKeyManager_Expecter) EncryptDek(dekKey interface{}, kek interface{}) *MockKeyManager_EncryptDek_Call {
	return &MockKeyManager_EncryptDek_Call{Call: _e.mock.On("EncryptDek", dekKey, kek)}
}

func (_c *MockKeyManager_EncryptDek_Call) Run(run func(dekKey []byte, kek *domain.Kek)) *MockKeyManager_EncryptDek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *domain.Kek
		if args[1] != nil {
			arg1 = args[1].(*domain.Kek)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManager_EncryptDek_Call) Return(ciphertext []byte, nonce []byte, err error) *MockKeyManager_EncryptDek_Call {
	_c.Call.Return(ciphertext, nonce, err)
	return _c
}

func (_c *MockKeyManager_EncryptDek_Call) RunAndReturn(run func(dekKey []byte, kek *domain.Kek) ([]byte, []byte, error)) *MockKeyManager_EncryptDek_Call {
	_c.Call.Return(run)
	return _c
}
