// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/allisson/secrets/internal/secrets/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretUseCase creates a new instance of MockSecretUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretUseCase {
	mock := &MockSecretUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretUseCase is an autogenerated mock type for the SecretUseCase type
type MockSecretUseCase struct {
	mock.Mock
}

type MockSecretUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretUseCase) EXPECT() *MockSecretUseCase_Expecter {
	return &MockSecretUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) CreateOrUpdate(ctx context.Context, path string, value []byte) (*domain.Secret, error) {
	ret := _mock.Called(ctx, path, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 *domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (*domain.Secret, error)); ok {
		return returnFunc(ctx, path, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) *domain.Secret); ok {
		r0 = returnFunc(ctx, path, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, path, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretUseCase_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockSecretUseCase_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - value []byte
func (_e *MockSecretUseCase_Expecter) CreateOrUpdate(ctx any, path any, value any) *MockSecretUseCase_CreateOrUpdate_Call {
	return &MockSecretUseCase_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, path, value)}
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) Run(run func(ctx context.Context, path string, value []byte)) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) Return(secret *domain.Secret, err error) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) RunAndReturn(run func(ctx context.Context, path string, value []byte) (*domain.Secret, error)) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) Delete(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretUseCase_Expecter) Delete(ctx any, path any) *MockSecretUseCase_Delete_Call {
	return &MockSecretUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockSecretUseCase_Delete_Call) Run(run func(ctx context.Context, path string)) *MockSecretUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_Delete_Call) Return(err error) *MockSecretUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockSecretUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) Get(ctx context.Context, path string) (*domain.Secret, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Secret, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Secret); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretUseCase_Expecter) Get(ctx any, path any) *MockSecretUseCase_Get_Call {
	return &MockSecretUseCase_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockSecretUseCase_Get_Call) Run(run func(ctx context.Context, path string)) *MockSecretUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_Get_Call) Return(secret *domain.Secret, err error) *MockSecretUseCase_Get_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretUseCase_Get_Call) RunAndReturn(run func(ctx context.Context, path string) (*domain.Secret, error)) *MockSecretUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByVersion provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) GetByVersion(ctx context.Context, path string, version uint) (*domain.Secret, error) {
	ret := _mock.Called(ctx, path, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByVersion")
	}

	var r0 *domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.Secret, error)); ok {
		return returnFunc(ctx, path, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) *domain.Secret); ok {
		r0 = returnFunc(ctx, path, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, path, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretUseCase_GetByVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByVersion'
type MockSecretUseCase_GetByVersion_Call struct {
	*mock.Call
}

// GetByVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - version uint
func (_e *MockSecretUseCase_Expecter) GetByVersion(ctx any, path any, version any) *MockSecretUseCase_GetByVersion_Call {
	return &MockSecretUseCase_GetByVersion_Call{Call: _e.mock.On("GetByVersion", ctx, path, version)}
}

func (_c *MockSecretUseCase_GetByVersion_Call) Run(run func(ctx context.Context, path string, version uint)) *MockSecretUseCase_GetByVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_GetByVersion_Call) Return(secret *domain.Secret, err error) *MockSecretUseCase_GetByVersion_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretUseCase_GetByVersion_Call) RunAndReturn(run func(ctx context.Context, path string, version uint) (*domain.Secret, error)) *MockSecretUseCase_GetByVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) ListCursor(ctx context.Context, afterPath *string, limit int) ([]*domain.Secret, error) {
	ret := _mock.Called(ctx, afterPath, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) ([]*domain.Secret, error)); ok {
		return returnFunc(ctx, afterPath, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) []*domain.Secret); ok {
		r0 = returnFunc(ctx, afterPath, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int) error); ok {
		r1 = returnFunc(ctx, afterPath, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretUseCase_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockSecretUseCase_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterPath *string
//   - limit int
func (_e *MockSecretUseCase_Expecter) ListCursor(ctx any, afterPath any, limit any) *MockSecretUseCase_ListCursor_Call {
	return &MockSecretUseCase_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterPath, limit)}
}

func (_c *MockSecretUseCase_ListCursor_Call) Run(run func(ctx context.Context, afterPath *string, limit int)) *MockSecretUseCase_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_ListCursor_Call) Return(secrets []*domain.Secret, err error) *MockSecretUseCase_ListCursor_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretUseCase_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterPath *string, limit int) ([]*domain.Secret, error)) *MockSecretUseCase_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeDeleted provides a mock function for the type MockSecretUseCase
func (_mock *MockSecretUseCase) PurgeDeleted(ctx context.Context, olderThanDays int, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, olderThanDays, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for PurgeDeleted")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) (int64, error)); ok {
		return returnFunc(ctx, olderThanDays, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) int64); ok {
		r0 = returnFunc(ctx, olderThanDays, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = returnFunc(ctx, olderThanDays, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretUseCase_PurgeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeDeleted'
type MockSecretUseCase_PurgeDeleted_Call struct {
	*mock.Call
}

// PurgeDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThanDays int
//   - dryRun bool
func (_e *MockSecretUseCase_Expecter) PurgeDeleted(ctx any, olderThanDays any, dryRun any) *MockSecretUseCase_PurgeDeleted_Call {
	return &MockSecretUseCase_PurgeDeleted_Call{Call: _e.mock.On("PurgeDeleted", ctx, olderThanDays, dryRun)}
}

func (_c *MockSecretUseCase_PurgeDeleted_Call) Run(run func(ctx context.Context, olderThanDays int, dryRun bool)) *MockSecretUseCase_PurgeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretUseCase_PurgeDeleted_Call) Return(n int64, err error) *MockSecretUseCase_PurgeDeleted_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretUseCase_PurgeDeleted_Call) RunAndReturn(run func(ctx context.Context, olderThanDays int, dryRun bool) (int64, error)) *MockSecretUseCase_PurgeDeleted_Call {
	_c.Call.Return(run)
	return _c
}
