// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/secrets/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, secret
func (_m *MockSecretRepository) Create(ctx context.Context, secret *domain.Secret) error {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *domain.Secret
func (_e *MockSecretRepository_Expecter) Create(ctx interface{}, secret interface{}) *MockSecretRepository_Create_Call {
	return &MockSecretRepository_Create_Call{Call: _e.mock.On("Create", ctx, secret)}
}

func (_c *MockSecretRepository_Create_Call) Run(run func(ctx context.Context, secret *domain.Secret)) *MockSecretRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Secret))
	})
	return _c
}

func (_c *MockSecretRepository_Create_Call) Return(_a0 error) *MockSecretRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Secret) error) *MockSecretRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, secretID
func (_m *MockSecretRepository) Delete(ctx context.Context, secretID uuid.UUID) error {
	ret := _m.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, secretID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID uuid.UUID
func (_e *MockSecretRepository_Expecter) Delete(ctx interface{}, secretID interface{}) *MockSecretRepository_Delete_Call {
	return &MockSecretRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, secretID)}
}

func (_c *MockSecretRepository_Delete_Call) Run(run func(ctx context.Context, secretID uuid.UUID)) *MockSecretRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSecretRepository_Delete_Call) Return(_a0 error) *MockSecretRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSecretRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPath provides a mock function with given fields: ctx, path
func (_m *MockSecretRepository) GetByPath(ctx context.Context, path string) (*domain.Secret, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetByPath")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Secret, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Secret); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_GetByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPath'
type MockSecretRepository_GetByPath_Call struct {
	*mock.Call
}

// GetByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretRepository_Expecter) GetByPath(ctx interface{}, path interface{}) *MockSecretRepository_GetByPath_Call {
	return &MockSecretRepository_GetByPath_Call{Call: _e.mock.On("GetByPath", ctx, path)}
}

func (_c *MockSecretRepository_GetByPath_Call) Run(run func(ctx context.Context, path string)) *MockSecretRepository_GetByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSecretRepository_GetByPath_Call) Return(_a0 *domain.Secret, _a1 error) *MockSecretRepository_GetByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_GetByPath_Call) RunAndReturn(run func(context.Context, string) (*domain.Secret, error)) *MockSecretRepository_GetByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPathAndVersion provides a mock function with given fields: ctx, path, version
func (_m *MockSecretRepository) GetByPathAndVersion(ctx context.Context, path string, version uint) (*domain.Secret, error) {
	ret := _m.Called(ctx, path, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByPathAndVersion")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.Secret, error)); ok {
		return rf(ctx, path, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) *domain.Secret); ok {
		r0 = rf(ctx, path, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, path, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretRepository_GetByPathAndVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPathAndVersion'
type MockSecretRepository_GetByPathAndVersion_Call struct {
	*mock.Call
}

// GetByPathAndVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - version uint
func (_e *MockSecretRepository_Expecter) GetByPathAndVersion(ctx interface{}, path interface{}, version interface{}) *MockSecretRepository_GetByPathAndVersion_Call {
	return &MockSecretRepository_GetByPathAndVersion_Call{Call: _e.mock.On("GetByPathAndVersion", ctx, path, version)}
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) Run(run func(ctx context.Context, path string, version uint)) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) Return(_a0 *domain.Secret, _a1 error) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) RunAndReturn(run func(context.Context, string, uint) (*domain.Secret, error)) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
