// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/allisson/secrets/internal/secrets/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSecretUseCase is an autogenerated mock type for the SecretUseCase type
type MockSecretUseCase struct {
	mock.Mock
}

type MockSecretUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretUseCase) EXPECT() *MockSecretUseCase_Expecter {
	return &MockSecretUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrUpdate provides a mock function with given fields: ctx, path, value
func (_m *MockSecretUseCase) CreateOrUpdate(ctx context.Context, path string, value []byte) (*domain.Secret, error) {
	ret := _m.Called(ctx, path, value)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (*domain.Secret, error)); ok {
		return rf(ctx, path, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *domain.Secret); ok {
		r0 = rf(ctx, path, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, path, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretUseCase_CreateOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdate'
type MockSecretUseCase_CreateOrUpdate_Call struct {
	*mock.Call
}

// CreateOrUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - value []byte
func (_e *MockSecretUseCase_Expecter) CreateOrUpdate(ctx interface{}, path interface{}, value interface{}) *MockSecretUseCase_CreateOrUpdate_Call {
	return &MockSecretUseCase_CreateOrUpdate_Call{Call: _e.mock.On("CreateOrUpdate", ctx, path, value)}
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) Run(run func(ctx context.Context, path string, value []byte)) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) Return(_a0 *domain.Secret, _a1 error) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretUseCase_CreateOrUpdate_Call) RunAndReturn(run func(context.Context, string, []byte) (*domain.Secret, error)) *MockSecretUseCase_CreateOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, path
func (_m *MockSecretUseCase) Delete(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSecretUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretUseCase_Expecter) Delete(ctx interface{}, path interface{}) *MockSecretUseCase_Delete_Call {
	return &MockSecretUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockSecretUseCase_Delete_Call) Run(run func(ctx context.Context, path string)) *MockSecretUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSecretUseCase_Delete_Call) Return(_a0 error) *MockSecretUseCase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretUseCase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSecretUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, path
func (_m *MockSecretUseCase) Get(ctx context.Context, path string) (*domain.Secret, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Secret, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Secret); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretUseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretUseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretUseCase_Expecter) Get(ctx interface{}, path interface{}) *MockSecretUseCase_Get_Call {
	return &MockSecretUseCase_Get_Call{Call: _e.mock.On("Get", ctx, path)}
}

func (_c *MockSecretUseCase_Get_Call) Run(run func(ctx context.Context, path string)) *MockSecretUseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSecretUseCase_Get_Call) Return(_a0 *domain.Secret, _a1 error) *MockSecretUseCase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretUseCase_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.Secret, error)) *MockSecretUseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretUseCase creates a new instance of MockSecretUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretUseCase {
	mock := &MockSecretUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
