// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/secrets/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) Create(ctx context.Context, secret *domain.Secret) error {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Secret) error); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *domain.Secret
func (_e *MockSecretRepository_Expecter) Create(ctx any, secret any) *MockSecretRepository_Create_Call {
	return &MockSecretRepository_Create_Call{Call: _e.mock.On("Create", ctx, secret)}
}

func (_c *MockSecretRepository_Create_Call) Run(run func(ctx context.Context, secret *domain.Secret)) *MockSecretRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Secret
		if args[1] != nil {
			arg1 = args[1].(*domain.Secret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_Create_Call) Return(err error) *MockSecretRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_Create_Call) RunAndReturn(run func(ctx context.Context, secret *domain.Secret) error) *MockSecretRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) Delete(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretRepository_Expecter) Delete(ctx any, path any) *MockSecretRepository_Delete_Call {
	return &MockSecretRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *MockSecretRepository_Delete_Call) Run(run func(ctx context.Context, path string)) *MockSecretRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_Delete_Call) Return(err error) *MockSecretRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockSecretRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPath provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetByPath(ctx context.Context, path string) (*domain.Secret, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetByPath")
	}

	var r0 *domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Secret, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Secret); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPath'
type MockSecretRepository_GetByPath_Call struct {
	*mock.Call
}

// GetByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSecretRepository_Expecter) GetByPath(ctx any, path any) *MockSecretRepository_GetByPath_Call {
	return &MockSecretRepository_GetByPath_Call{Call: _e.mock.On("GetByPath", ctx, path)}
}

func (_c *MockSecretRepository_GetByPath_Call) Run(run func(ctx context.Context, path string)) *MockSecretRepository_GetByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetByPath_Call) Return(secret *domain.Secret, err error) *MockSecretRepository_GetByPath_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepository_GetByPath_Call) RunAndReturn(run func(ctx context.Context, path string) (*domain.Secret, error)) *MockSecretRepository_GetByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPathAndVersion provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetByPathAndVersion(ctx context.Context, path string, version uint) (*domain.Secret, error) {
	ret := _mock.Called(ctx, path, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByPathAndVersion")
	}

	var r0 *domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.Secret, error)); ok {
		return returnFunc(ctx, path, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) *domain.Secret); ok {
		r0 = returnFunc(ctx, path, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, path, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetByPathAndVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPathAndVersion'
type MockSecretRepository_GetByPathAndVersion_Call struct {
	*mock.Call
}

// GetByPathAndVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - version uint
func (_e *MockSecretRepository_Expecter) GetByPathAndVersion(ctx any, path any, version any) *MockSecretRepository_GetByPathAndVersion_Call {
	return &MockSecretRepository_GetByPathAndVersion_Call{Call: _e.mock.On("GetByPathAndVersion", ctx, path, version)}
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) Run(run func(ctx context.Context, path string, version uint)) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) Return(secret *domain.Secret, err error) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretRepository_GetByPathAndVersion_Call) RunAndReturn(run func(ctx context.Context, path string, version uint) (*domain.Secret, error)) *MockSecretRepository_GetByPathAndVersion_Call {
	_c.Call.Return(run)
	return _c
}

// HardDelete provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) HardDelete(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, olderThan, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) (int64, error)); ok {
		return returnFunc(ctx, olderThan, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) int64); ok {
		r0 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, bool) error); ok {
		r1 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_HardDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HardDelete'
type MockSecretRepository_HardDelete_Call struct {
	*mock.Call
}

// HardDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
//   - dryRun bool
func (_e *MockSecretRepository_Expecter) HardDelete(ctx any, olderThan any, dryRun any) *MockSecretRepository_HardDelete_Call {
	return &MockSecretRepository_HardDelete_Call{Call: _e.mock.On("HardDelete", ctx, olderThan, dryRun)}
}

func (_c *MockSecretRepository_HardDelete_Call) Run(run func(ctx context.Context, olderThan time.Time, dryRun bool)) *MockSecretRepository_HardDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_HardDelete_Call) Return(n int64, err error) *MockSecretRepository_HardDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretRepository_HardDelete_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error)) *MockSecretRepository_HardDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) ListCursor(ctx context.Context, afterPath *string, limit int) ([]*domain.Secret, error) {
	ret := _mock.Called(ctx, afterPath, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) ([]*domain.Secret, error)); ok {
		return returnFunc(ctx, afterPath, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) []*domain.Secret); ok {
		r0 = returnFunc(ctx, afterPath, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int) error); ok {
		r1 = returnFunc(ctx, afterPath, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockSecretRepository_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterPath *string
//   - limit int
func (_e *MockSecretRepository_Expecter) ListCursor(ctx any, afterPath any, limit any) *MockSecretRepository_ListCursor_Call {
	return &MockSecretRepository_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterPath, limit)}
}

func (_c *MockSecretRepository_ListCursor_Call) Run(run func(ctx context.Context, afterPath *string, limit int)) *MockSecretRepository_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_ListCursor_Call) Return(secrets []*domain.Secret, err error) *MockSecretRepository_ListCursor_Call {
	_c.Call.Return(secrets, err)
	return _c
}

func (_c *MockSecretRepository_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterPath *string, limit int) ([]*domain.Secret, error)) *MockSecretRepository_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}
