// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/allisson/secrets/internal/transit/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransitKeyRepository creates a new instance of MockTransitKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransitKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransitKeyRepository {
	mock := &MockTransitKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransitKeyRepository is an autogenerated mock type for the TransitKeyRepository type
type MockTransitKeyRepository struct {
	mock.Mock
}

type MockTransitKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransitKeyRepository) EXPECT() *MockTransitKeyRepository_Expecter {
	return &MockTransitKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) Create(ctx context.Context, transitKey *domain.TransitKey) error {
	ret := _mock.Called(ctx, transitKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TransitKey) error); ok {
		r0 = returnFunc(ctx, transitKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransitKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransitKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transitKey *domain.TransitKey
func (_e *MockTransitKeyRepository_Expecter) Create(ctx any, transitKey any) *MockTransitKeyRepository_Create_Call {
	return &MockTransitKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, transitKey)}
}

func (_c *MockTransitKeyRepository_Create_Call) Run(run func(ctx context.Context, transitKey *domain.TransitKey)) *MockTransitKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TransitKey
		if args[1] != nil {
			arg1 = args[1].(*domain.TransitKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) Return(err error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransitKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, transitKey *domain.TransitKey) error) *MockTransitKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransitKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransitKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransitKeyRepository_Expecter) Delete(ctx any, name any) *MockTransitKeyRepository_Delete_Call {
	return &MockTransitKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockTransitKeyRepository_Delete_Call) Run(run func(ctx context.Context, name string)) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) Return(err error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransitKeyRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockTransitKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) GetByName(ctx context.Context, name string) (*domain.TransitKey, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.TransitKey, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.TransitKey); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTransitKeyRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransitKeyRepository_Expecter) GetByName(ctx any, name any) *MockTransitKeyRepository_GetByName_Call {
	return &MockTransitKeyRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTransitKeyRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) Return(transitKey *domain.TransitKey, err error) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.TransitKey, error)) *MockTransitKeyRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNameAndVersion provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) GetByNameAndVersion(ctx context.Context, name string, version uint) (*domain.TransitKey, error) {
	ret := _mock.Called(ctx, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetByNameAndVersion")
	}

	var r0 *domain.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.TransitKey, error)); ok {
		return returnFunc(ctx, name, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) *domain.TransitKey); ok {
		r0 = returnFunc(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_GetByNameAndVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNameAndVersion'
type MockTransitKeyRepository_GetByNameAndVersion_Call struct {
	*mock.Call
}

// GetByNameAndVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version uint
func (_e *MockTransitKeyRepository_Expecter) GetByNameAndVersion(ctx any, name any, version any) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	return &MockTransitKeyRepository_GetByNameAndVersion_Call{Call: _e.mock.On("GetByNameAndVersion", ctx, name, version)}
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Run(run func(ctx context.Context, name string, version uint)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) Return(transitKey *domain.TransitKey, err error) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyRepository_GetByNameAndVersion_Call) RunAndReturn(run func(ctx context.Context, name string, version uint) (*domain.TransitKey, error)) *MockTransitKeyRepository_GetByNameAndVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitKey provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) GetTransitKey(ctx context.Context, name string, version uint) (*domain.TransitKey, error) {
	ret := _mock.Called(ctx, name, version)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitKey")
	}

	var r0 *domain.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) (*domain.TransitKey, error)); ok {
		return returnFunc(ctx, name, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint) *domain.TransitKey); ok {
		r0 = returnFunc(ctx, name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = returnFunc(ctx, name, version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_GetTransitKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitKey'
type MockTransitKeyRepository_GetTransitKey_Call struct {
	*mock.Call
}

// GetTransitKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - version uint
func (_e *MockTransitKeyRepository_Expecter) GetTransitKey(ctx any, name any, version any) *MockTransitKeyRepository_GetTransitKey_Call {
	return &MockTransitKeyRepository_GetTransitKey_Call{Call: _e.mock.On("GetTransitKey", ctx, name, version)}
}

func (_c *MockTransitKeyRepository_GetTransitKey_Call) Run(run func(ctx context.Context, name string, version uint)) *MockTransitKeyRepository_GetTransitKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_GetTransitKey_Call) Return(transitKey *domain.TransitKey, err error) *MockTransitKeyRepository_GetTransitKey_Call {
	_c.Call.Return(transitKey, err)
	return _c
}

func (_c *MockTransitKeyRepository_GetTransitKey_Call) RunAndReturn(run func(ctx context.Context, name string, version uint) (*domain.TransitKey, error)) *MockTransitKeyRepository_GetTransitKey_Call {
	_c.Call.Return(run)
	return _c
}

// HardDelete provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) HardDelete(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error) {
	ret := _mock.Called(ctx, olderThan, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) (int64, error)); ok {
		return returnFunc(ctx, olderThan, dryRun)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, bool) int64); ok {
		r0 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, bool) error); ok {
		r1 = returnFunc(ctx, olderThan, dryRun)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_HardDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HardDelete'
type MockTransitKeyRepository_HardDelete_Call struct {
	*mock.Call
}

// HardDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Time
//   - dryRun bool
func (_e *MockTransitKeyRepository_Expecter) HardDelete(ctx any, olderThan any, dryRun any) *MockTransitKeyRepository_HardDelete_Call {
	return &MockTransitKeyRepository_HardDelete_Call{Call: _e.mock.On("HardDelete", ctx, olderThan, dryRun)}
}

func (_c *MockTransitKeyRepository_HardDelete_Call) Run(run func(ctx context.Context, olderThan time.Time, dryRun bool)) *MockTransitKeyRepository_HardDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_HardDelete_Call) Return(n int64, err error) *MockTransitKeyRepository_HardDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTransitKeyRepository_HardDelete_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Time, dryRun bool) (int64, error)) *MockTransitKeyRepository_HardDelete_Call {
	_c.Call.Return(run)
	return _c
}

// ListCursor provides a mock function for the type MockTransitKeyRepository
func (_mock *MockTransitKeyRepository) ListCursor(ctx context.Context, afterName *string, limit int) ([]*domain.TransitKey, error) {
	ret := _mock.Called(ctx, afterName, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCursor")
	}

	var r0 []*domain.TransitKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) ([]*domain.TransitKey, error)); ok {
		return returnFunc(ctx, afterName, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, int) []*domain.TransitKey); ok {
		r0 = returnFunc(ctx, afterName, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TransitKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, int) error); ok {
		r1 = returnFunc(ctx, afterName, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransitKeyRepository_ListCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCursor'
type MockTransitKeyRepository_ListCursor_Call struct {
	*mock.Call
}

// ListCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - afterName *string
//   - limit int
func (_e *MockTransitKeyRepository_Expecter) ListCursor(ctx any, afterName any, limit any) *MockTransitKeyRepository_ListCursor_Call {
	return &MockTransitKeyRepository_ListCursor_Call{Call: _e.mock.On("ListCursor", ctx, afterName, limit)}
}

func (_c *MockTransitKeyRepository_ListCursor_Call) Run(run func(ctx context.Context, afterName *string, limit int)) *MockTransitKeyRepository_ListCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransitKeyRepository_ListCursor_Call) Return(transitKeys []*domain.TransitKey, err error) *MockTransitKeyRepository_ListCursor_Call {
	_c.Call.Return(transitKeys, err)
	return _c
}

func (_c *MockTransitKeyRepository_ListCursor_Call) RunAndReturn(run func(ctx context.Context, afterName *string, limit int) ([]*domain.TransitKey, error)) *MockTransitKeyRepository_ListCursor_Call {
	_c.Call.Return(run)
	return _c
}
