// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/allisson/secrets/internal/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// CompareSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) CompareSecret(plainSecret string, hashedSecret string) bool {
	ret := _mock.Called(plainSecret, hashedSecret)

	if len(ret) == 0 {
		panic("no return value specified for CompareSecret")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(plainSecret, hashedSecret)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSecretService_CompareSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareSecret'
type MockSecretService_CompareSecret_Call struct {
	*mock.Call
}

// CompareSecret is a helper method to define mock.On call
//   - plainSecret string
//   - hashedSecret string
func (_e *MockSecretService_Expecter) CompareSecret(plainSecret interface{}, hashedSecret interface{}) *MockSecretService_CompareSecret_Call {
	return &MockSecretService_CompareSecret_Call{Call: _e.mock.On("CompareSecret", plainSecret, hashedSecret)}
}

func (_c *MockSecretService_CompareSecret_Call) Run(run func(plainSecret string, hashedSecret string)) *MockSecretService_CompareSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretService_CompareSecret_Call) Return(b bool) *MockSecretService_CompareSecret_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSecretService_CompareSecret_Call) RunAndReturn(run func(plainSecret string, hashedSecret string) bool) *MockSecretService_CompareSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) GenerateSecret() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecret")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSecretService_GenerateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecret'
type MockSecretService_GenerateSecret_Call struct {
	*mock.Call
}

// GenerateSecret is a helper method to define mock.On call
func (_e *MockSecretService_Expecter) GenerateSecret() *MockSecretService_GenerateSecret_Call {
	return &MockSecretService_GenerateSecret_Call{Call: _e.mock.On("GenerateSecret")}
}

func (_c *MockSecretService_GenerateSecret_Call) Run(run func()) *MockSecretService_GenerateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) Return(plainSecret string, hashedSecret string, error1 error) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(plainSecret, hashedSecret, error1)
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) RunAndReturn(run func() (string, string, error)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// HashSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) HashSecret(plainSecret string) (string, error) {
	ret := _mock.Called(plainSecret)

	if len(ret) == 0 {
		panic("no return value specified for HashSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_HashSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashSecret'
type MockSecretService_HashSecret_Call struct {
	*mock.Call
}

// HashSecret is a helper method to define mock.On call
//   - plainSecret string
func (_e *MockSecretService_Expecter) HashSecret(plainSecret interface{}) *MockSecretService_HashSecret_Call {
	return &MockSecretService_HashSecret_Call{Call: _e.mock.On("HashSecret", plainSecret)}
}

func (_c *MockSecretService_HashSecret_Call) Run(run func(plainSecret string)) *MockSecretService_HashSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretService_HashSecret_Call) Return(hashedSecret string, error1 error) *MockSecretService_HashSecret_Call {
	_c.Call.Return(hashedSecret, error1)
	return _c
}

func (_c *MockSecretService_HashSecret_Call) RunAndReturn(run func(plainSecret string) (string, error)) *MockSecretService_HashSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateToken() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GenerateToken() *MockTokenService_GenerateToken_Call {
	return &MockTokenService_GenerateToken_Call{Call: _e.mock.On("GenerateToken")}
}

func (_c *MockTokenService_GenerateToken_Call) Run(run func()) *MockTokenService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) Return(plainToken string, tokenHash string, error1 error) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(plainToken, tokenHash, error1)
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) RunAndReturn(run func() (string, string, error)) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) HashToken(plainToken string) string {
	ret := _mock.Called(plainToken)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenService_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - plainToken string
func (_e *MockTokenService_Expecter) HashToken(plainToken interface{}) *MockTokenService_HashToken_Call {
	return &MockTokenService_HashToken_Call{Call: _e.mock.On("HashToken", plainToken)}
}

func (_c *MockTokenService_HashToken_Call) Run(run func(plainToken string)) *MockTokenService_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_HashToken_Call) Return(s string) *MockTokenService_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_HashToken_Call) RunAndReturn(run func(plainToken string) string) *MockTokenService_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditSigner creates a new instance of MockAuditSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditSigner {
	mock := &MockAuditSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditSigner is an autogenerated mock type for the AuditSigner type
type MockAuditSigner struct {
	mock.Mock
}

type MockAuditSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditSigner) EXPECT() *MockAuditSigner_Expecter {
	return &MockAuditSigner_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type MockAuditSigner
func (_mock *MockAuditSigner) Sign(kekKey []byte, log *domain.AuditLog) ([]byte, error) {
	ret := _mock.Called(kekKey, log)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, *domain.AuditLog) ([]byte, error)); ok {
		return returnFunc(kekKey, log)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, *domain.AuditLog) []byte); ok {
		r0 = returnFunc(kekKey, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, *domain.AuditLog) error); ok {
		r1 = returnFunc(kekKey, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockAuditSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - kekKey []byte
//   - log *domain.AuditLog
func (_e *MockAuditSigner_Expecter) Sign(kekKey interface{}, log interface{}) *MockAuditSigner_Sign_Call {
	return &MockAuditSigner_Sign_Call{Call: _e.mock.On("Sign", kekKey, log)}
}

func (_c *MockAuditSigner_Sign_Call) Run(run func(kekKey []byte, log *domain.AuditLog)) *MockAuditSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditSigner_Sign_Call) Return(bytes []byte, err error) *MockAuditSigner_Sign_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAuditSigner_Sign_Call) RunAndReturn(run func(kekKey []byte, log *domain.AuditLog) ([]byte, error)) *MockAuditSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockAuditSigner
func (_mock *MockAuditSigner) Verify(kekKey []byte, log *domain.AuditLog) error {
	ret := _mock.Called(kekKey, log)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, *domain.AuditLog) error); ok {
		r0 = returnFunc(kekKey, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditSigner_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockAuditSigner_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - kekKey []byte
//   - log *domain.AuditLog
func (_e *MockAuditSigner_Expecter) Verify(kekKey interface{}, log interface{}) *MockAuditSigner_Verify_Call {
	return &MockAuditSigner_Verify_Call{Call: _e.mock.On("Verify", kekKey, log)}
}

func (_c *MockAuditSigner_Verify_Call) Run(run func(kekKey []byte, log *domain.AuditLog)) *MockAuditSigner_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *domain.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditSigner_Verify_Call) Return(err error) *MockAuditSigner_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditSigner_Verify_Call) RunAndReturn(run func(kekKey []byte, log *domain.AuditLog) error) *MockAuditSigner_Verify_Call {
	_c.Call.Return(run)
	return _c
}
