// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretService creates a new instance of MockSecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretService {
	mock := &MockSecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretService is an autogenerated mock type for the SecretService type
type MockSecretService struct {
	mock.Mock
}

type MockSecretService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretService) EXPECT() *MockSecretService_Expecter {
	return &MockSecretService_Expecter{mock: &_m.Mock}
}

// CompareSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) CompareSecret(plainSecret string, hashedSecret string) bool {
	ret := _mock.Called(plainSecret, hashedSecret)

	if len(ret) == 0 {
		panic("no return value specified for CompareSecret")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(plainSecret, hashedSecret)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSecretService_CompareSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareSecret'
type MockSecretService_CompareSecret_Call struct {
	*mock.Call
}

// CompareSecret is a helper method to define mock.On call
//   - plainSecret string
//   - hashedSecret string
func (_e *MockSecretService_Expecter) CompareSecret(plainSecret interface{}, hashedSecret interface{}) *MockSecretService_CompareSecret_Call {
	return &MockSecretService_CompareSecret_Call{Call: _e.mock.On("CompareSecret", plainSecret, hashedSecret)}
}

func (_c *MockSecretService_CompareSecret_Call) Run(run func(plainSecret string, hashedSecret string)) *MockSecretService_CompareSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretService_CompareSecret_Call) Return(b bool) *MockSecretService_CompareSecret_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSecretService_CompareSecret_Call) RunAndReturn(run func(plainSecret string, hashedSecret string) bool) *MockSecretService_CompareSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) GenerateSecret() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecret")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSecretService_GenerateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecret'
type MockSecretService_GenerateSecret_Call struct {
	*mock.Call
}

// GenerateSecret is a helper method to define mock.On call
func (_e *MockSecretService_Expecter) GenerateSecret() *MockSecretService_GenerateSecret_Call {
	return &MockSecretService_GenerateSecret_Call{Call: _e.mock.On("GenerateSecret")}
}

func (_c *MockSecretService_GenerateSecret_Call) Run(run func()) *MockSecretService_GenerateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) Return(plainSecret string, hashedSecret string, error1 error) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(plainSecret, hashedSecret, error1)
	return _c
}

func (_c *MockSecretService_GenerateSecret_Call) RunAndReturn(run func() (string, string, error)) *MockSecretService_GenerateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// HashSecret provides a mock function for the type MockSecretService
func (_mock *MockSecretService) HashSecret(plainSecret string) (string, error) {
	ret := _mock.Called(plainSecret)

	if len(ret) == 0 {
		panic("no return value specified for HashSecret")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plainSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plainSecret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plainSecret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretService_HashSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashSecret'
type MockSecretService_HashSecret_Call struct {
	*mock.Call
}

// HashSecret is a helper method to define mock.On call
//   - plainSecret string
func (_e *MockSecretService_Expecter) HashSecret(plainSecret interface{}) *MockSecretService_HashSecret_Call {
	return &MockSecretService_HashSecret_Call{Call: _e.mock.On("HashSecret", plainSecret)}
}

func (_c *MockSecretService_HashSecret_Call) Run(run func(plainSecret string)) *MockSecretService_HashSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretService_HashSecret_Call) Return(hashedSecret string, error1 error) *MockSecretService_HashSecret_Call {
	_c.Call.Return(hashedSecret, error1)
	return _c
}

func (_c *MockSecretService_HashSecret_Call) RunAndReturn(run func(plainSecret string) (string, error)) *MockSecretService_HashSecret_Call {
	_c.Call.Return(run)
	return _c
}
