// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with no fields
func (_m *MockTokenService) GenerateToken() (string, string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func() (string, string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTokenService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockTokenService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GenerateToken() *MockTokenService_GenerateToken_Call {
	return &MockTokenService_GenerateToken_Call{Call: _e.mock.On("GenerateToken")}
}

func (_c *MockTokenService_GenerateToken_Call) Run(run func()) *MockTokenService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) Return(plainToken string, tokenHash string, error2 error) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(plainToken, tokenHash, error2)
	return _c
}

func (_c *MockTokenService_GenerateToken_Call) RunAndReturn(run func() (string, string, error)) *MockTokenService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function with given fields: plainToken
func (_m *MockTokenService) HashToken(plainToken string) string {
	ret := _m.Called(plainToken)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(plainToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenService_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenService_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - plainToken string
func (_e *MockTokenService_Expecter) HashToken(plainToken interface{}) *MockTokenService_HashToken_Call {
	return &MockTokenService_HashToken_Call{Call: _e.mock.On("HashToken", plainToken)}
}

func (_c *MockTokenService_HashToken_Call) Run(run func(plainToken string)) *MockTokenService_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenService_HashToken_Call) Return(_a0 string) *MockTokenService_HashToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenService_HashToken_Call) RunAndReturn(run func(string) string) *MockTokenService_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
